  INFO root [2019-05-08 10:03:20,708] - 
  INFO root [2019-05-08 10:03:20,708] - -----------------------------------------------------------------------------------------


  INFO root [2019-05-08 10:03:20,708] - Resmgr::initialize: KBE_ROOT=D:/kbengine/
  INFO root [2019-05-08 10:03:20,708] - Resmgr::initialize: KBE_RES_PATH=D:/kbengine/kbe/res/;D:/kbengine/server_assets/;D:/kbengine/server_assets/scripts/;D:/kbengine/server_assets/res/
  INFO root [2019-05-08 10:03:20,708] - Resmgr::initialize: KBE_BIN_PATH=D:/kbengine/kbe/bin/server/
  INFO root [2019-05-08 10:03:20,714] - NetworkInterface::initialize(INTERNAL-TCP): bound to all interfaces with default route interface on 192.168.56.1 ( 192.168.56.1:30099 )
  INFO root [2019-05-08 10:03:20,714] - NetworkInterface::initialize(INTERNAL-TCP): address 192.168.56.1:30099, SOMAXCONN=5.
  WARN root [2019-05-08 10:03:20,714] - invalid UID(0) <= 0, please check UID for environment! automatically set to 3960.
  INFO root [2019-05-08 10:03:20,725] - ---- interfaces Version: 2.4.5. ScriptVersion: 0.1.0. Pythoncore: 3.7.3. Protocol: 96E445E56B9E460E561358C2D6E9F43B. Config: Debug X86. Built: 09:54:37 May  8 2019. AppID: 3000. UID: 3960. PID: 12996 ----
  INFO root [2019-05-08 10:03:20,725] - Server error_name: Intel(R) Core(TM) i5-6300HQ CPU @ 2.30GHz with 2097151kB RAM
  INFO root [2019-05-08 10:03:20,725] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2019-05-08 10:03:20,725] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
  INFO root [2019-05-08 10:03:20,919] - Script::install(): is successfully, Python=(3.7.3 (default, May  8 2019, 09:53:38) [MSC v.1916 32 bit (Intel)])!
  INFO root [2019-05-08 10:03:20,919] - Script::install(): KBExtra is successfully!
S_INFO root [2019-05-08 10:03:21,124] - onInterfaceAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2019-05-08 10:03:21,144] - TelnetServer server is running on port 33000
  INFO root [2019-05-08 10:03:21,494] - ---- interfaces is running ----
 DEBUG root [2019-05-08 10:03:21,494] - Components::process(): Request for the process of identity...
  INFO root [2019-05-08 10:03:28,833] - Components::process(): Found all the components!
  INFO root [2019-05-08 10:03:29,809] - ServerApp::onRegisterNewApp: uid:3960, username:error_name, componentType:dbmgr, componentID:4000, globalorderID=-1, grouporderID=-1, intaddr:192.168.56.1, intport:64889, extaddr:nonsupport, extport:0,  from 127.0.0.1:64891/0/0/0.
  INFO root [2019-05-08 10:03:29,809] - Components::addComponent: reset orderLog, uid=3960!
  INFO root [2019-05-08 10:03:29,809] - Components::addComponent[dbmgr], uid=3960, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  WARN root [2019-05-08 10:05:17,728] - TCPPacketReceiver::processPendingEvents(127.0.0.1:64891): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
  INFO root [2019-05-08 10:05:17,734] - Components::removeComponentByChannel: dbmgr : 4000, Normal exit!
