  INFO root [2019-10-01 16:22:59,481] - 
  INFO root [2019-10-01 16:22:59,481] - -----------------------------------------------------------------------------------------


  INFO root [2019-10-01 16:22:59,481] - Resmgr::initialize: KBE_ROOT=D:/kbengine/
  INFO root [2019-10-01 16:22:59,481] - Resmgr::initialize: KBE_RES_PATH=D:/kbengine/kbe/res/;D:/kbengine/BattleOfBalls_assets/;D:/kbengine/BattleOfBalls_assets/scripts/;D:/kbengine/BattleOfBalls_assets/res/
  INFO root [2019-10-01 16:22:59,481] - Resmgr::initialize: KBE_BIN_PATH=D:/kbengine/kbe/bin/server/
  INFO root [2019-10-01 16:22:59,501] - NetworkInterface::initialize(EXTERNAL-TCP): bound to all interfaces with default route interface on 10.12.231.110 ( 10.12.231.110:20013 )
  INFO root [2019-10-01 16:22:59,501] - NetworkInterface::initialize(EXTERNAL-TCP): address 10.12.231.110:20013, SOMAXCONN=128.
  INFO root [2019-10-01 16:22:59,501] - NetworkInterface::initialize(INTERNAL-TCP): bound to all interfaces with default route interface on 10.12.231.110 ( 10.12.231.110:53350 )
  INFO root [2019-10-01 16:22:59,501] - NetworkInterface::initialize(INTERNAL-TCP): address 10.12.231.110:53350, SOMAXCONN=128.
  INFO root [2019-10-01 16:22:59,501] - server-configs:
  INFO root [2019-10-01 16:22:59,501] - 	internalTcpAddr : 10.12.231.110:53350
  INFO root [2019-10-01 16:22:59,501] - 	externalTcpAddr : 10.12.231.110:20013
  INFO root [2019-10-01 16:22:59,501] - 	componentID : 9000
  INFO root [2019-10-01 16:22:59,586] - 
  INFO root [2019-10-01 16:22:59,586] - -----------------------------------------------------------------------------------------


  INFO root [2019-10-01 16:22:59,591] - Resmgr::initialize: KBE_ROOT=D:/kbengine/
  INFO root [2019-10-01 16:22:59,591] - Resmgr::initialize: KBE_RES_PATH=D:/kbengine/kbe/res/;D:/kbengine/BattleOfBalls_assets/;D:/kbengine/BattleOfBalls_assets/scripts/;D:/kbengine/BattleOfBalls_assets/res/
  INFO root [2019-10-01 16:22:59,591] - Resmgr::initialize: KBE_BIN_PATH=D:/kbengine/kbe/bin/server/
  INFO root [2019-10-01 16:22:59,601] - NetworkInterface::initialize(EXTERNAL-TCP): bound to all interfaces with default route interface on 10.12.231.110 ( 10.12.231.110:20013 )
  INFO root [2019-10-01 16:22:59,606] - NetworkInterface::initialize(EXTERNAL-TCP): address 10.12.231.110:20013, SOMAXCONN=128.
  INFO root [2019-10-01 16:22:59,606] - NetworkInterface::initialize(INTERNAL-TCP): bound to all interfaces with default route interface on 10.12.231.110 ( 10.12.231.110:53351 )
  INFO root [2019-10-01 16:22:59,606] - NetworkInterface::initialize(INTERNAL-TCP): address 10.12.231.110:53351, SOMAXCONN=128.
  INFO root [2019-10-01 16:22:59,606] - server-configs:
  INFO root [2019-10-01 16:22:59,606] - 	internalTcpAddr : 10.12.231.110:53351
  INFO root [2019-10-01 16:22:59,611] - 	externalTcpAddr : 10.12.231.110:20013
  INFO root [2019-10-01 16:22:59,611] - 	componentID : 9000
  WARN root [2019-10-01 16:22:59,666] - invalid UID(0) <= 0, please check UID for environment! automatically set to 41181.
  INFO root [2019-10-01 16:22:59,716] - Components::findLogger: found logger, addr:10.12.231.110:53293
  INFO root [2019-10-01 16:22:59,716] - Components::addComponent: reset orderLog, uid=41181!
  INFO root [2019-10-01 16:22:59,716] - Components::addComponent[logger], uid=41181, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2019-10-01 16:22:59,741] - ---- loginapp Version: 2.4.5. ScriptVersion: 0.1.0. Pythoncore: 3.7.3. Protocol: CE9FF53F4E85387EE4455C7191269324. Config: Debug X86. Built: 09:58:16 May  8 2019. AppID: 9000. UID: 41181. PID: 8500 ----
  INFO root [2019-10-01 16:22:59,741] - Server error_name: Intel(R) Core(TM) i5-6300HQ CPU @ 2.30GHz with 2097151kB RAM
  INFO root [2019-10-01 16:22:59,741] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2019-10-01 16:22:59,741] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
  WARN root [2019-10-01 16:22:59,761] - invalid UID(0) <= 0, please check UID for environment! automatically set to 41181.
  INFO root [2019-10-01 16:22:59,821] - Components::findLogger: found logger, addr:10.12.231.110:53293
  INFO root [2019-10-01 16:22:59,821] - Components::addComponent: reset orderLog, uid=41181!
  INFO root [2019-10-01 16:22:59,821] - Components::addComponent[logger], uid=41181, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2019-10-01 16:22:59,821] - ---- loginapp Version: 2.4.5. ScriptVersion: 0.1.0. Pythoncore: 3.7.3. Protocol: CE9FF53F4E85387EE4455C7191269324. Config: Debug X86. Built: 09:58:16 May  8 2019. AppID: 9000. UID: 41181. PID: 12568 ----
  INFO root [2019-10-01 16:22:59,821] - Server error_name: Intel(R) Core(TM) i5-6300HQ CPU @ 2.30GHz with 2097151kB RAM
  INFO root [2019-10-01 16:22:59,821] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2019-10-01 16:22:59,821] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
  INFO root [2019-10-01 16:22:59,951] - Script::install(): is successfully, Python=(3.7.3 (default, May  8 2019, 09:53:38) [MSC v.1916 32 bit (Intel)])!
  INFO root [2019-10-01 16:22:59,951] - Script::install(): KBExtra is successfully!
S_INFO root [2019-10-01 16:22:59,991] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2019-10-01 16:22:59,991] - TelnetServer server is running on port 31000
  INFO root [2019-10-01 16:23:00,031] - Script::install(): is successfully, Python=(3.7.3 (default, May  8 2019, 09:53:38) [MSC v.1916 32 bit (Intel)])!
  INFO root [2019-10-01 16:23:00,031] - Script::install(): KBExtra is successfully!
S_INFO root [2019-10-01 16:23:00,041] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2019-10-01 16:23:00,041] - TelnetServer server is running on port 31001
  INFO root [2019-10-01 16:23:00,397] - ---- loginapp is running ----
 DEBUG root [2019-10-01 16:23:00,397] - Components::process(): Request for the process of identity...
  INFO root [2019-10-01 16:23:00,431] - ---- loginapp is running ----
 DEBUG root [2019-10-01 16:23:00,431] - Components::process(): Request for the process of identity...
 ERROR root [2019-10-01 16:23:00,596] - Components::process: found loginapp, addr:10.12.231.110:53350
 ERROR root [2019-10-01 16:23:00,597] - ServerApp::onIdentityillegal: The current process and loginapp(componentID=9000 ->conflicted???, pid=8500, addr=10.12.231.110) conflict, the process will exit!
Can modify the components-CID and UID to avoid conflict.
  INFO root [2019-10-01 16:23:00,597] - Shutdowner::onShutdownBegin: shutting down(period=1, tickPeriod=1)
S_INFO root [2019-10-01 16:23:00,597] - onLoginAppShutDown()
  WARN root [2019-10-01 16:23:00,597] - Forwarding logs to logger[10.12.231.110:53293/0/0/0]...
  INFO root [2019-10-01 16:23:04,631] - EventDispatcher()::~EventDispatcher: Num timers = 2
  WARN root [2019-10-01 16:23:06,641] - Forwarding logs to logger[10.12.231.110:53293/0/0/0]...
 ERROR root [2019-10-01 16:23:08,721] - Components::removeComponentByChannel: logger : 2000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=77809011328, lastReceivedTime=77788420088, inactivityExceptionPeriod=599369038)
  INFO root [2019-10-01 16:23:08,721] - The following logs sent to logger failed:
  WARN root [2019-10-01 16:23:08,721] - ==> [2019-10-01 16:23:08 722] TCPPacketReceiver::processPendingEvents(10.12.231.110:53293): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2019-10-01 16:23:08,721] - ==> [2019-10-01 16:23:08 723] Components::removeComponentByChannel: logger : 2000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=77809011328, lastReceivedTime=77788420088, inactivityExceptionPeriod=599369038)
  INFO root [2019-10-01 16:23:15,111] - 
  INFO root [2019-10-01 16:23:15,116] - -----------------------------------------------------------------------------------------


  INFO root [2019-10-01 16:23:15,116] - Resmgr::initialize: KBE_ROOT=D:/kbengine/
  INFO root [2019-10-01 16:23:15,116] - Resmgr::initialize: KBE_RES_PATH=D:/kbengine/kbe/res/;D:/kbengine/BattleOfBalls_assets/;D:/kbengine/BattleOfBalls_assets/scripts/;D:/kbengine/BattleOfBalls_assets/res/
  INFO root [2019-10-01 16:23:15,116] - Resmgr::initialize: KBE_BIN_PATH=D:/kbengine/kbe/bin/server/
  INFO root [2019-10-01 16:23:15,121] - NetworkInterface::initialize(EXTERNAL-TCP): bound to all interfaces with default route interface on 10.12.231.110 ( 10.12.231.110:20013 )
  INFO root [2019-10-01 16:23:15,121] - NetworkInterface::initialize(EXTERNAL-TCP): address 10.12.231.110:20013, SOMAXCONN=128.
  INFO root [2019-10-01 16:23:15,131] - NetworkInterface::initialize(INTERNAL-TCP): bound to all interfaces with default route interface on 10.12.231.110 ( 10.12.231.110:53370 )
  INFO root [2019-10-01 16:23:15,131] - NetworkInterface::initialize(INTERNAL-TCP): address 10.12.231.110:53370, SOMAXCONN=128.
  INFO root [2019-10-01 16:23:15,131] - server-configs:
  INFO root [2019-10-01 16:23:15,131] - 	internalTcpAddr : 10.12.231.110:53370
  INFO root [2019-10-01 16:23:15,131] - 	externalTcpAddr : 10.12.231.110:20013
  INFO root [2019-10-01 16:23:15,131] - 	componentID : 9000
  WARN root [2019-10-01 16:23:15,332] - invalid UID(0) <= 0, please check UID for environment! automatically set to 41181.
  INFO root [2019-10-01 16:23:15,411] - Components::findLogger: found logger, addr:10.12.231.110:53361
  INFO root [2019-10-01 16:23:15,411] - Components::addComponent: reset orderLog, uid=41181!
  INFO root [2019-10-01 16:23:15,411] - Components::addComponent[logger], uid=41181, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2019-10-01 16:23:21,431] - ---- loginapp Version: 2.4.5. ScriptVersion: 0.1.0. Pythoncore: 3.7.3. Protocol: CE9FF53F4E85387EE4455C7191269324. Config: Debug X86. Built: 09:58:16 May  8 2019. AppID: 9000. UID: 41181. PID: 11556 ----
  INFO root [2019-10-01 16:23:21,431] - Server error_name: Intel(R) Core(TM) i5-6300HQ CPU @ 2.30GHz with 2097151kB RAM
  INFO root [2019-10-01 16:23:21,431] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2019-10-01 16:23:21,431] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
  INFO root [2019-10-01 16:23:21,641] - Script::install(): is successfully, Python=(3.7.3 (default, May  8 2019, 09:53:38) [MSC v.1916 32 bit (Intel)])!
  INFO root [2019-10-01 16:23:21,641] - Script::install(): KBExtra is successfully!
S_INFO root [2019-10-01 16:23:21,651] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2019-10-01 16:23:21,651] - TelnetServer server is running on port 31000
  INFO root [2019-10-01 16:23:22,026] - ---- loginapp is running ----
 DEBUG root [2019-10-01 16:23:22,026] - Components::process(): Request for the process of identity...
  WARN root [2019-10-01 16:23:28,231] - Forwarding logs to logger[10.12.231.110:53361/0/0/0]...
 ERROR root [2019-10-01 16:29:48,761] - Components::removeComponentByChannel: logger : 2000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=81809465958, lastReceivedTime=81768402047, inactivityExceptionPeriod=599499873)
  INFO root [2019-10-01 16:29:48,771] - The following logs sent to logger failed:
  WARN root [2019-10-01 16:29:48,771] - ==> [2019-10-01 16:29:48 767] TCPPacketReceiver::processPendingEvents(10.12.231.110:53361): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2019-10-01 16:29:48,771] - ==> [2019-10-01 16:29:48 769] Components::removeComponentByChannel: logger : 2000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=81809465958, lastReceivedTime=81768402047, inactivityExceptionPeriod=599499873)
  WARN root [2019-10-01 16:29:48,856] - TCPPacketReceiver::processPendingEvents(10.12.231.110:53362): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2019-10-01 16:29:48,856] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=81810364699, lastReceivedTime=81768802046, inactivityExceptionPeriod=599499873)
  INFO root [2019-10-01 16:29:48,920] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [2019-10-01 16:29:48,920] - onLoginAppShutDown()
  INFO root [2019-10-01 16:29:48,931] - Shutdowner::onShutdown: shutting down
  INFO root [2019-10-01 16:29:48,931] - Shutdowner::onShutdownEnd: shutting down
  INFO root [2019-10-01 16:29:48,940] - Script::uninstall(): is successfully!
 DEBUG root [2019-10-01 16:29:48,940] - ThreadPool::destroy(): starting size 2.
  WARN root [2019-10-01 16:29:49,251] - ThreadPool::destroy(): waiting for thread(2)[0x152e3c0,0x152e358,], try=1
  INFO root [2019-10-01 16:31:35,411] - 
  INFO root [2019-10-01 16:31:35,411] - -----------------------------------------------------------------------------------------


  INFO root [2019-10-01 16:31:35,411] - Resmgr::initialize: KBE_ROOT=D:/kbengine/
  INFO root [2019-10-01 16:31:35,411] - Resmgr::initialize: KBE_RES_PATH=D:/kbengine/kbe/res/;D:/kbengine/BattleOfBalls_assets/;D:/kbengine/BattleOfBalls_assets/scripts/;D:/kbengine/BattleOfBalls_assets/res/
  INFO root [2019-10-01 16:31:35,411] - Resmgr::initialize: KBE_BIN_PATH=D:/kbengine/kbe/bin/server/
  INFO root [2019-10-01 16:31:35,431] - NetworkInterface::initialize(EXTERNAL-TCP): bound to all interfaces with default route interface on 10.12.231.110 ( 10.12.231.110:20013 )
  INFO root [2019-10-01 16:31:35,431] - NetworkInterface::initialize(EXTERNAL-TCP): address 10.12.231.110:20013, SOMAXCONN=128.
  INFO root [2019-10-01 16:31:35,436] - NetworkInterface::initialize(INTERNAL-TCP): bound to all interfaces with default route interface on 10.12.231.110 ( 10.12.231.110:53497 )
  INFO root [2019-10-01 16:31:35,436] - NetworkInterface::initialize(INTERNAL-TCP): address 10.12.231.110:53497, SOMAXCONN=128.
  INFO root [2019-10-01 16:31:35,436] - server-configs:
  INFO root [2019-10-01 16:31:35,436] - 	internalTcpAddr : 10.12.231.110:53497
  INFO root [2019-10-01 16:31:35,436] - 	externalTcpAddr : 10.12.231.110:20013
  INFO root [2019-10-01 16:31:35,436] - 	componentID : 9000
  WARN root [2019-10-01 16:31:35,590] - invalid UID(0) <= 0, please check UID for environment! automatically set to 41181.
  INFO root [2019-10-01 16:31:35,660] - Components::findLogger: found logger, addr:10.12.231.110:53488
  INFO root [2019-10-01 16:31:35,660] - Components::addComponent: reset orderLog, uid=41181!
  INFO root [2019-10-01 16:31:35,660] - Components::addComponent[logger], uid=41181, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2019-10-01 16:31:35,668] - ---- loginapp Version: 2.4.5. ScriptVersion: 0.1.0. Pythoncore: 3.7.3. Protocol: CE9FF53F4E85387EE4455C7191269324. Config: Debug X86. Built: 09:58:16 May  8 2019. AppID: 9000. UID: 41181. PID: 9588 ----
  INFO root [2019-10-01 16:31:35,668] - Server error_name: Intel(R) Core(TM) i5-6300HQ CPU @ 2.30GHz with 2097151kB RAM
  INFO root [2019-10-01 16:31:35,668] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2019-10-01 16:31:35,668] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
  INFO root [2019-10-01 16:31:35,866] - Script::install(): is successfully, Python=(3.7.3 (default, May  8 2019, 09:53:38) [MSC v.1916 32 bit (Intel)])!
  INFO root [2019-10-01 16:31:35,866] - Script::install(): KBExtra is successfully!
S_INFO root [2019-10-01 16:31:35,876] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2019-10-01 16:31:35,876] - TelnetServer server is running on port 31000
  INFO root [2019-10-01 16:31:36,272] - ---- loginapp is running ----
 DEBUG root [2019-10-01 16:31:36,275] - Components::process(): Request for the process of identity...
  WARN root [2019-10-01 16:31:42,521] - Forwarding logs to logger[10.12.231.110:53488/0/0/0]...
 ERROR root [2019-10-01 16:34:00,880] - Components::removeComponentByChannel: logger : 2000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=84330614269, lastReceivedTime=84066762256, inactivityExceptionPeriod=599499041)
  INFO root [2019-10-01 16:34:00,885] - The following logs sent to logger failed:
  WARN root [2019-10-01 16:34:00,885] - ==> [2019-10-01 16:34:00 882] TCPPacketReceiver::processPendingEvents(10.12.231.110:53488): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2019-10-01 16:34:00,885] - ==> [2019-10-01 16:34:00 883] Components::removeComponentByChannel: logger : 2000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=84330614269, lastReceivedTime=84066762256, inactivityExceptionPeriod=599499041)
  WARN root [2019-10-01 16:34:00,940] - TCPPacketReceiver::processPendingEvents(10.12.231.110:53490): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2019-10-01 16:34:00,940] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=84331254414, lastReceivedTime=84067905320, inactivityExceptionPeriod=599499041)
  INFO root [2019-10-01 16:34:00,940] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [2019-10-01 16:34:00,940] - onLoginAppShutDown()
  INFO root [2019-10-01 16:34:00,940] - Shutdowner::onShutdown: shutting down
  INFO root [2019-10-01 16:34:00,950] - Shutdowner::onShutdownEnd: shutting down
  INFO root [2019-10-01 16:34:00,955] - Script::uninstall(): is successfully!
 DEBUG root [2019-10-01 16:34:00,955] - ThreadPool::destroy(): starting size 2.
  WARN root [2019-10-01 16:34:01,261] - ThreadPool::destroy(): waiting for thread(2)[0x150b798,0x150b868,], try=1
  INFO root [2019-10-01 16:35:23,700] - 
  INFO root [2019-10-01 16:35:23,700] - -----------------------------------------------------------------------------------------


  INFO root [2019-10-01 16:35:23,700] - Resmgr::initialize: KBE_ROOT=D:/kbengine/
  INFO root [2019-10-01 16:35:23,700] - Resmgr::initialize: KBE_RES_PATH=D:/kbengine/kbe/res/;D:/kbengine/BattleOfBalls_assets/;D:/kbengine/BattleOfBalls_assets/scripts/;D:/kbengine/BattleOfBalls_assets/res/
  INFO root [2019-10-01 16:35:23,700] - Resmgr::initialize: KBE_BIN_PATH=D:/kbengine/kbe/bin/server/
  INFO root [2019-10-01 16:35:23,717] - NetworkInterface::initialize(EXTERNAL-TCP): bound to all interfaces with default route interface on 10.12.231.110 ( 10.12.231.110:20013 )
  INFO root [2019-10-01 16:35:23,717] - NetworkInterface::initialize(EXTERNAL-TCP): address 10.12.231.110:20013, SOMAXCONN=128.
  INFO root [2019-10-01 16:35:23,720] - NetworkInterface::initialize(INTERNAL-TCP): bound to all interfaces with default route interface on 10.12.231.110 ( 10.12.231.110:53570 )
  INFO root [2019-10-01 16:35:23,720] - NetworkInterface::initialize(INTERNAL-TCP): address 10.12.231.110:53570, SOMAXCONN=128.
  INFO root [2019-10-01 16:35:23,720] - server-configs:
  INFO root [2019-10-01 16:35:23,720] - 	internalTcpAddr : 10.12.231.110:53570
  INFO root [2019-10-01 16:35:23,720] - 	externalTcpAddr : 10.12.231.110:20013
  INFO root [2019-10-01 16:35:23,725] - 	componentID : 9000
  WARN root [2019-10-01 16:35:23,875] - invalid UID(0) <= 0, please check UID for environment! automatically set to 41181.
  INFO root [2019-10-01 16:35:23,890] - Components::findLogger: found logger, addr:10.12.231.110:53564
  INFO root [2019-10-01 16:35:23,890] - Components::addComponent: reset orderLog, uid=41181!
  INFO root [2019-10-01 16:35:23,890] - Components::addComponent[logger], uid=41181, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2019-10-01 16:35:23,895] - ---- loginapp Version: 2.4.5. ScriptVersion: 0.1.0. Pythoncore: 3.7.3. Protocol: CE9FF53F4E85387EE4455C7191269324. Config: Debug X86. Built: 09:58:16 May  8 2019. AppID: 9000. UID: 41181. PID: 13052 ----
  INFO root [2019-10-01 16:35:23,895] - Server error_name: Intel(R) Core(TM) i5-6300HQ CPU @ 2.30GHz with 2097151kB RAM
  INFO root [2019-10-01 16:35:23,895] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2019-10-01 16:35:23,898] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
  INFO root [2019-10-01 16:35:24,135] - Script::install(): is successfully, Python=(3.7.3 (default, May  8 2019, 09:53:38) [MSC v.1916 32 bit (Intel)])!
  INFO root [2019-10-01 16:35:24,135] - Script::install(): KBExtra is successfully!
S_INFO root [2019-10-01 16:35:24,152] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2019-10-01 16:35:24,155] - TelnetServer server is running on port 31000
  INFO root [2019-10-01 16:35:24,584] - ---- loginapp is running ----
 DEBUG root [2019-10-01 16:35:24,584] - Components::process(): Request for the process of identity...
  WARN root [2019-10-01 16:35:30,830] - Forwarding logs to logger[10.12.231.110:53564/0/0/0]...
 ERROR root [2019-10-01 16:36:54,495] - Components::removeComponentByChannel: logger : 2000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=86066732824, lastReceivedTime=86054918416, inactivityExceptionPeriod=599499425)
  INFO root [2019-10-01 16:36:54,498] - The following logs sent to logger failed:
  WARN root [2019-10-01 16:36:54,499] - ==> [2019-10-01 16:36:54 488] TCPPacketReceiver::processPendingEvents(10.12.231.110:53564): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2019-10-01 16:36:54,499] - ==> [2019-10-01 16:36:54 495] Components::removeComponentByChannel: logger : 2000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=86066732824, lastReceivedTime=86054918416, inactivityExceptionPeriod=599499425)
  WARN root [2019-10-01 16:36:54,589] - TCPPacketReceiver::processPendingEvents(10.12.231.110:53565): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2019-10-01 16:36:54,592] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=86067701278, lastReceivedTime=86055963607, inactivityExceptionPeriod=599499425)
  INFO root [2019-10-01 16:36:54,602] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [2019-10-01 16:36:54,603] - onLoginAppShutDown()
  INFO root [2019-10-01 16:36:54,604] - Shutdowner::onShutdown: shutting down
  INFO root [2019-10-01 16:36:54,604] - Shutdowner::onShutdownEnd: shutting down
  INFO root [2019-10-01 16:36:54,618] - Script::uninstall(): is successfully!
 DEBUG root [2019-10-01 16:36:54,618] - ThreadPool::destroy(): starting size 2.
  WARN root [2019-10-01 16:36:54,920] - ThreadPool::destroy(): waiting for thread(2)[0x165de78,0x165da68,], try=1
 DEBUG root [2019-10-01 16:36:55,321] - TPThread::~TPThread(): 0x165de78
 DEBUG root [2019-10-01 16:36:55,321] - TPThread::~TPThread(): 0x165da68
 DEBUG root [2019-10-01 16:36:55,321] - ThreadPool::destroy(): successfully!
 DEBUG root [2019-10-01 16:36:55,345] - Bundle::destroyObjPool(): size 20.
 DEBUG root [2019-10-01 16:36:55,346] - Channel::destroyObjPool(): size 14.
 DEBUG root [2019-10-01 16:36:55,346] - TCPPacket::destroyObjPool(): size 3.
 DEBUG root [2019-10-01 16:36:55,346] - UDPPacket::destroyObjPool(): size 2.
 DEBUG root [2019-10-01 16:36:55,346] - EndPoint::destroyObjPool(): size 13.
 DEBUG root [2019-10-01 16:36:55,347] - Address::destroyObjPool(): size 0.
 DEBUG root [2019-10-01 16:36:55,347] - TCPPacketReceiver::destroyObjPool(): size 0.
 DEBUG root [2019-10-01 16:36:55,347] - UDPPacketReceiver::destroyObjPool(): size 0.
  INFO root [2019-10-01 16:36:55,348] - loginapp(9000) has shut down.
  INFO root [2019-10-01 16:38:48,555] - 
  INFO root [2019-10-01 16:38:48,555] - -----------------------------------------------------------------------------------------


  INFO root [2019-10-01 16:38:48,555] - Resmgr::initialize: KBE_ROOT=D:/kbengine/
  INFO root [2019-10-01 16:38:48,555] - Resmgr::initialize: KBE_RES_PATH=D:/kbengine/kbe/res/;D:/kbengine/BattleOfBalls_assets/;D:/kbengine/BattleOfBalls_assets/scripts/;D:/kbengine/BattleOfBalls_assets/res/
  INFO root [2019-10-01 16:38:48,555] - Resmgr::initialize: KBE_BIN_PATH=D:/kbengine/kbe/bin/server/
  INFO root [2019-10-01 16:38:48,565] - NetworkInterface::initialize(EXTERNAL-TCP): bound to all interfaces with default route interface on 10.12.231.110 ( 10.12.231.110:20013 )
  INFO root [2019-10-01 16:38:48,565] - NetworkInterface::initialize(EXTERNAL-TCP): address 10.12.231.110:20013, SOMAXCONN=128.
  INFO root [2019-10-01 16:38:48,572] - NetworkInterface::initialize(INTERNAL-TCP): bound to all interfaces with default route interface on 10.12.231.110 ( 10.12.231.110:53647 )
  INFO root [2019-10-01 16:38:48,572] - NetworkInterface::initialize(INTERNAL-TCP): address 10.12.231.110:53647, SOMAXCONN=128.
  INFO root [2019-10-01 16:38:48,575] - server-configs:
  INFO root [2019-10-01 16:38:48,575] - 	internalTcpAddr : 10.12.231.110:53647
  INFO root [2019-10-01 16:38:48,575] - 	externalTcpAddr : 10.12.231.110:20013
  INFO root [2019-10-01 16:38:48,575] - 	componentID : 9000
  WARN root [2019-10-01 16:38:48,754] - invalid UID(0) <= 0, please check UID for environment! automatically set to 41181.
  INFO root [2019-10-01 16:38:48,824] - Components::findLogger: found logger, addr:10.12.231.110:53641
  INFO root [2019-10-01 16:38:48,824] - Components::addComponent: reset orderLog, uid=41181!
  INFO root [2019-10-01 16:38:48,824] - Components::addComponent[logger], uid=41181, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2019-10-01 16:38:54,880] - ---- loginapp Version: 2.4.5. ScriptVersion: 0.1.0. Pythoncore: 3.7.3. Protocol: CE9FF53F4E85387EE4455C7191269324. Config: Debug X86. Built: 09:58:16 May  8 2019. AppID: 9000. UID: 41181. PID: 7028 ----
  INFO root [2019-10-01 16:38:54,880] - Server error_name: Intel(R) Core(TM) i5-6300HQ CPU @ 2.30GHz with 2097151kB RAM
  INFO root [2019-10-01 16:38:54,880] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2019-10-01 16:38:54,880] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
  INFO root [2019-10-01 16:38:55,091] - Script::install(): is successfully, Python=(3.7.3 (default, May  8 2019, 09:53:38) [MSC v.1916 32 bit (Intel)])!
  INFO root [2019-10-01 16:38:55,091] - Script::install(): KBExtra is successfully!
S_INFO root [2019-10-01 16:38:55,100] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2019-10-01 16:38:55,100] - TelnetServer server is running on port 31000
  INFO root [2019-10-01 16:38:55,480] - ---- loginapp is running ----
 DEBUG root [2019-10-01 16:38:55,480] - Components::process(): Request for the process of identity...
  WARN root [2019-10-01 16:39:01,624] - Forwarding logs to logger[10.12.231.110:53641/0/0/0]...
 ERROR root [2019-10-01 16:41:28,558] - Components::removeComponentByChannel: logger : 2000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=88807375220, lastReceivedTime=88702739406, inactivityExceptionPeriod=599500000)
  INFO root [2019-10-01 16:41:28,564] - The following logs sent to logger failed:
  WARN root [2019-10-01 16:41:28,565] - ==> [2019-10-01 16:41:28 559] TCPPacketReceiver::processPendingEvents(10.12.231.110:53641): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2019-10-01 16:41:28,566] - ==> [2019-10-01 16:41:28 559] Components::removeComponentByChannel: logger : 2000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=88807375220, lastReceivedTime=88702739406, inactivityExceptionPeriod=599500000)
  WARN root [2019-10-01 16:41:28,663] - TCPPacketReceiver::processPendingEvents(10.12.231.110:53642): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2019-10-01 16:41:28,669] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=88808474488, lastReceivedTime=88703685941, inactivityExceptionPeriod=599500000)
  INFO root [2019-10-01 16:41:28,674] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [2019-10-01 16:41:28,675] - onLoginAppShutDown()
  INFO root [2019-10-01 16:41:28,675] - Shutdowner::onShutdown: shutting down
  INFO root [2019-10-01 16:41:28,675] - Shutdowner::onShutdownEnd: shutting down
  INFO root [2019-10-01 16:41:28,685] - Script::uninstall(): is successfully!
 DEBUG root [2019-10-01 16:41:28,686] - ThreadPool::destroy(): starting size 2.
  WARN root [2019-10-01 16:41:28,987] - ThreadPool::destroy(): waiting for thread(2)[0x1709d00,0x17093a8,], try=1
 DEBUG root [2019-10-01 16:41:29,389] - TPThread::~TPThread(): 0x1709d00
 DEBUG root [2019-10-01 16:41:29,389] - TPThread::~TPThread(): 0x17093a8
 DEBUG root [2019-10-01 16:41:29,390] - ThreadPool::destroy(): successfully!
 DEBUG root [2019-10-01 16:41:29,419] - Bundle::destroyObjPool(): size 20.
 DEBUG root [2019-10-01 16:41:29,419] - Channel::destroyObjPool(): size 14.
 DEBUG root [2019-10-01 16:41:29,420] - TCPPacket::destroyObjPool(): size 3.
 DEBUG root [2019-10-01 16:41:29,421] - UDPPacket::destroyObjPool(): size 2.
 DEBUG root [2019-10-01 16:41:29,421] - EndPoint::destroyObjPool(): size 13.
 DEBUG root [2019-10-01 16:41:29,421] - Address::destroyObjPool(): size 0.
 DEBUG root [2019-10-01 16:41:29,421] - TCPPacketReceiver::destroyObjPool(): size 0.
 DEBUG root [2019-10-01 16:41:29,421] - UDPPacketReceiver::destroyObjPool(): size 0.
  INFO root [2019-10-01 16:41:29,421] - loginapp(9000) has shut down.
  INFO root [2019-10-01 16:41:53,062] - 
  INFO root [2019-10-01 16:41:53,064] - -----------------------------------------------------------------------------------------


  INFO root [2019-10-01 16:41:53,064] - Resmgr::initialize: KBE_ROOT=D:/kbengine/
  INFO root [2019-10-01 16:41:53,064] - Resmgr::initialize: KBE_RES_PATH=D:/kbengine/kbe/res/;D:/kbengine/BattleOfBalls_assets/;D:/kbengine/BattleOfBalls_assets/scripts/;D:/kbengine/BattleOfBalls_assets/res/
  INFO root [2019-10-01 16:41:53,064] - Resmgr::initialize: KBE_BIN_PATH=D:/kbengine/kbe/bin/server/
  INFO root [2019-10-01 16:41:53,094] - NetworkInterface::initialize(EXTERNAL-TCP): bound to all interfaces with default route interface on 10.12.231.110 ( 10.12.231.110:20013 )
  INFO root [2019-10-01 16:41:53,094] - NetworkInterface::initialize(EXTERNAL-TCP): address 10.12.231.110:20013, SOMAXCONN=128.
  INFO root [2019-10-01 16:41:53,094] - NetworkInterface::initialize(INTERNAL-TCP): bound to all interfaces with default route interface on 10.12.231.110 ( 10.12.231.110:53723 )
  INFO root [2019-10-01 16:41:53,100] - NetworkInterface::initialize(INTERNAL-TCP): address 10.12.231.110:53723, SOMAXCONN=128.
  INFO root [2019-10-01 16:41:53,101] - server-configs:
  INFO root [2019-10-01 16:41:53,101] - 	internalTcpAddr : 10.12.231.110:53723
  INFO root [2019-10-01 16:41:53,101] - 	externalTcpAddr : 10.12.231.110:20013
  INFO root [2019-10-01 16:41:53,101] - 	componentID : 9000
  WARN root [2019-10-01 16:41:53,256] - invalid UID(0) <= 0, please check UID for environment! automatically set to 41181.
  INFO root [2019-10-01 16:41:53,260] - Components::findLogger: found logger, addr:10.12.231.110:53717
  INFO root [2019-10-01 16:41:53,260] - Components::addComponent: reset orderLog, uid=41181!
  INFO root [2019-10-01 16:41:53,260] - Components::addComponent[logger], uid=41181, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2019-10-01 16:41:59,190] - ---- loginapp Version: 2.4.5. ScriptVersion: 0.1.0. Pythoncore: 3.7.3. Protocol: CE9FF53F4E85387EE4455C7191269324. Config: Debug X86. Built: 09:58:16 May  8 2019. AppID: 9000. UID: 41181. PID: 9252 ----
  INFO root [2019-10-01 16:41:59,190] - Server error_name: Intel(R) Core(TM) i5-6300HQ CPU @ 2.30GHz with 2097151kB RAM
  INFO root [2019-10-01 16:41:59,191] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2019-10-01 16:41:59,191] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
  INFO root [2019-10-01 16:41:59,410] - Script::install(): is successfully, Python=(3.7.3 (default, May  8 2019, 09:53:38) [MSC v.1916 32 bit (Intel)])!
  INFO root [2019-10-01 16:41:59,410] - Script::install(): KBExtra is successfully!
S_INFO root [2019-10-01 16:41:59,424] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2019-10-01 16:41:59,425] - TelnetServer server is running on port 31000
  INFO root [2019-10-01 16:41:59,883] - ---- loginapp is running ----
 DEBUG root [2019-10-01 16:41:59,884] - Components::process(): Request for the process of identity...
  WARN root [2019-10-01 16:42:06,038] - Forwarding logs to logger[10.12.231.110:53717/0/0/0]...
 ERROR root [2019-10-01 16:45:04,196] - Components::removeComponentByChannel: logger : 2000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=90963749766, lastReceivedTime=90847374391, inactivityExceptionPeriod=599500064)
  INFO root [2019-10-01 16:45:04,205] - The following logs sent to logger failed:
  WARN root [2019-10-01 16:45:04,205] - ==> [2019-10-01 16:45:04 192] TCPPacketReceiver::processPendingEvents(10.12.231.110:53717): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2019-10-01 16:45:04,206] - ==> [2019-10-01 16:45:04 197] Components::removeComponentByChannel: logger : 2000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=90963749766, lastReceivedTime=90847374391, inactivityExceptionPeriod=599500064)
  WARN root [2019-10-01 16:45:04,342] - TCPPacketReceiver::processPendingEvents(10.12.231.110:53719): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2019-10-01 16:45:04,358] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=90965366603, lastReceivedTime=90850051623, inactivityExceptionPeriod=599500064)
  INFO root [2019-10-01 16:45:04,374] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [2019-10-01 16:45:04,374] - onLoginAppShutDown()
  INFO root [2019-10-01 16:45:04,374] - Shutdowner::onShutdown: shutting down
  INFO root [2019-10-01 16:45:04,374] - Shutdowner::onShutdownEnd: shutting down
  INFO root [2019-10-01 16:45:04,384] - Script::uninstall(): is successfully!
 DEBUG root [2019-10-01 16:45:04,384] - ThreadPool::destroy(): starting size 2.
  WARN root [2019-10-01 16:45:04,686] - ThreadPool::destroy(): waiting for thread(2)[0x15dadd8,0x15db458,], try=1
 DEBUG root [2019-10-01 16:45:05,092] - TPThread::~TPThread(): 0x15dadd8
 DEBUG root [2019-10-01 16:45:05,092] - TPThread::~TPThread(): 0x15db458
 DEBUG root [2019-10-01 16:45:05,093] - ThreadPool::destroy(): successfully!
 DEBUG root [2019-10-01 16:45:05,119] - Bundle::destroyObjPool(): size 20.
 DEBUG root [2019-10-01 16:45:05,120] - Channel::destroyObjPool(): size 14.
 DEBUG root [2019-10-01 16:45:05,120] - TCPPacket::destroyObjPool(): size 3.
 DEBUG root [2019-10-01 16:45:05,120] - UDPPacket::destroyObjPool(): size 2.
 DEBUG root [2019-10-01 16:45:05,120] - EndPoint::destroyObjPool(): size 13.
 DEBUG root [2019-10-01 16:45:05,121] - Address::destroyObjPool(): size 0.
 DEBUG root [2019-10-01 16:45:05,121] - TCPPacketReceiver::destroyObjPool(): size 0.
 DEBUG root [2019-10-01 16:45:05,121] - UDPPacketReceiver::destroyObjPool(): size 0.
  INFO root [2019-10-01 16:45:05,121] - loginapp(9000) has shut down.
  INFO root [2019-10-01 16:47:27,894] - 
  INFO root [2019-10-01 16:47:27,902] - -----------------------------------------------------------------------------------------


  INFO root [2019-10-01 16:47:27,902] - Resmgr::initialize: KBE_ROOT=D:/kbengine/
  INFO root [2019-10-01 16:47:27,902] - Resmgr::initialize: KBE_RES_PATH=D:/kbengine/kbe/res/;D:/kbengine/BattleOfBalls_assets/;D:/kbengine/BattleOfBalls_assets/scripts/;D:/kbengine/BattleOfBalls_assets/res/
  INFO root [2019-10-01 16:47:27,902] - Resmgr::initialize: KBE_BIN_PATH=D:/kbengine/kbe/bin/server/
  INFO root [2019-10-01 16:47:27,924] - NetworkInterface::initialize(EXTERNAL-TCP): bound to all interfaces with default route interface on 10.12.231.110 ( 10.12.231.110:20013 )
  INFO root [2019-10-01 16:47:27,924] - NetworkInterface::initialize(EXTERNAL-TCP): address 10.12.231.110:20013, SOMAXCONN=128.
  INFO root [2019-10-01 16:47:27,930] - NetworkInterface::initialize(INTERNAL-TCP): bound to all interfaces with default route interface on 10.12.231.110 ( 10.12.231.110:53814 )
  INFO root [2019-10-01 16:47:27,930] - NetworkInterface::initialize(INTERNAL-TCP): address 10.12.231.110:53814, SOMAXCONN=128.
  INFO root [2019-10-01 16:47:27,930] - server-configs:
  INFO root [2019-10-01 16:47:27,930] - 	internalTcpAddr : 10.12.231.110:53814
  INFO root [2019-10-01 16:47:27,930] - 	externalTcpAddr : 10.12.231.110:20013
  INFO root [2019-10-01 16:47:27,930] - 	componentID : 9000
  WARN root [2019-10-01 16:47:28,097] - invalid UID(0) <= 0, please check UID for environment! automatically set to 41181.
  INFO root [2019-10-01 16:47:28,155] - Components::findLogger: found logger, addr:10.12.231.110:53806
  INFO root [2019-10-01 16:47:28,157] - Components::addComponent: reset orderLog, uid=41181!
  INFO root [2019-10-01 16:47:28,157] - Components::addComponent[logger], uid=41181, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2019-10-01 16:47:34,190] - ---- loginapp Version: 2.4.5. ScriptVersion: 0.1.0. Pythoncore: 3.7.3. Protocol: CE9FF53F4E85387EE4455C7191269324. Config: Debug X86. Built: 09:58:16 May  8 2019. AppID: 9000. UID: 41181. PID: 12000 ----
  INFO root [2019-10-01 16:47:34,190] - Server error_name: Intel(R) Core(TM) i5-6300HQ CPU @ 2.30GHz with 2097151kB RAM
  INFO root [2019-10-01 16:47:34,190] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2019-10-01 16:47:34,190] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
  INFO root [2019-10-01 16:47:34,390] - Script::install(): is successfully, Python=(3.7.3 (default, May  8 2019, 09:53:38) [MSC v.1916 32 bit (Intel)])!
  INFO root [2019-10-01 16:47:34,390] - Script::install(): KBExtra is successfully!
S_INFO root [2019-10-01 16:47:34,400] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2019-10-01 16:47:34,400] - TelnetServer server is running on port 31000
  INFO root [2019-10-01 16:47:34,735] - ---- loginapp is running ----
 DEBUG root [2019-10-01 16:47:34,735] - Components::process(): Request for the process of identity...
  WARN root [2019-10-01 16:47:38,490] - BundleBroadcast::BundleBroadcast: Cannot bind to port 20011, errorno=10048
  WARN root [2019-10-01 16:47:41,533] - Forwarding logs to logger[10.12.231.110:53806/0/0/0]...
 ERROR root [2019-10-01 16:49:22,958] - Components::removeComponentByChannel: logger : 2000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=93551373974, lastReceivedTime=93295968487, inactivityExceptionPeriod=599500064)
  INFO root [2019-10-01 16:49:22,961] - The following logs sent to logger failed:
  WARN root [2019-10-01 16:49:22,961] - ==> [2019-10-01 16:49:22 955] TCPPacketReceiver::processPendingEvents(10.12.231.110:53806): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2019-10-01 16:49:22,962] - ==> [2019-10-01 16:49:22 959] Components::removeComponentByChannel: logger : 2000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=93551373974, lastReceivedTime=93295968487, inactivityExceptionPeriod=599500064)
  WARN root [2019-10-01 16:49:23,017] - TCPPacketReceiver::processPendingEvents(10.12.231.110:53807): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2019-10-01 16:49:23,019] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=93551981286, lastReceivedTime=93298111989, inactivityExceptionPeriod=599500064)
  INFO root [2019-10-01 16:49:23,022] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [2019-10-01 16:49:23,024] - onLoginAppShutDown()
  INFO root [2019-10-01 16:49:23,024] - Shutdowner::onShutdown: shutting down
  INFO root [2019-10-01 16:49:23,024] - Shutdowner::onShutdownEnd: shutting down
  INFO root [2019-10-01 16:49:23,035] - Script::uninstall(): is successfully!
 DEBUG root [2019-10-01 16:49:23,035] - ThreadPool::destroy(): starting size 2.
  WARN root [2019-10-01 16:49:23,337] - ThreadPool::destroy(): waiting for thread(2)[0x146aa50,0x146ab88,], try=1
  INFO root [2019-10-01 16:50:11,290] - 
  INFO root [2019-10-01 16:50:11,292] - -----------------------------------------------------------------------------------------


  INFO root [2019-10-01 16:50:11,293] - Resmgr::initialize: KBE_ROOT=D:/kbengine/
  INFO root [2019-10-01 16:50:11,293] - Resmgr::initialize: KBE_RES_PATH=D:/kbengine/kbe/res/;D:/kbengine/BattleOfBalls_assets/;D:/kbengine/BattleOfBalls_assets/scripts/;D:/kbengine/BattleOfBalls_assets/res/
  INFO root [2019-10-01 16:50:11,293] - Resmgr::initialize: KBE_BIN_PATH=D:/kbengine/kbe/bin/server/
  INFO root [2019-10-01 16:50:11,312] - NetworkInterface::initialize(EXTERNAL-TCP): bound to all interfaces with default route interface on 10.12.231.110 ( 10.12.231.110:20013 )
  INFO root [2019-10-01 16:50:11,316] - NetworkInterface::initialize(EXTERNAL-TCP): address 10.12.231.110:20013, SOMAXCONN=128.
  INFO root [2019-10-01 16:50:11,319] - NetworkInterface::initialize(INTERNAL-TCP): bound to all interfaces with default route interface on 10.12.231.110 ( 10.12.231.110:53890 )
  INFO root [2019-10-01 16:50:11,321] - NetworkInterface::initialize(INTERNAL-TCP): address 10.12.231.110:53890, SOMAXCONN=128.
  INFO root [2019-10-01 16:50:11,321] - server-configs:
  INFO root [2019-10-01 16:50:11,321] - 	internalTcpAddr : 10.12.231.110:53890
  INFO root [2019-10-01 16:50:11,321] - 	externalTcpAddr : 10.12.231.110:20013
  INFO root [2019-10-01 16:50:11,321] - 	componentID : 9000
  WARN root [2019-10-01 16:50:11,481] - invalid UID(0) <= 0, please check UID for environment! automatically set to 41181.
  INFO root [2019-10-01 16:50:11,609] - Components::findLogger: found logger, addr:10.12.231.110:53884
  INFO root [2019-10-01 16:50:11,610] - Components::addComponent: reset orderLog, uid=41181!
  INFO root [2019-10-01 16:50:11,610] - Components::addComponent[logger], uid=41181, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2019-10-01 16:50:17,531] - ---- loginapp Version: 2.4.5. ScriptVersion: 0.1.0. Pythoncore: 3.7.3. Protocol: CE9FF53F4E85387EE4455C7191269324. Config: Debug X86. Built: 09:58:16 May  8 2019. AppID: 9000. UID: 41181. PID: 10716 ----
  INFO root [2019-10-01 16:50:17,531] - Server error_name: Intel(R) Core(TM) i5-6300HQ CPU @ 2.30GHz with 2097151kB RAM
  INFO root [2019-10-01 16:50:17,532] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2019-10-01 16:50:17,532] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
  INFO root [2019-10-01 16:50:17,762] - Script::install(): is successfully, Python=(3.7.3 (default, May  8 2019, 09:53:38) [MSC v.1916 32 bit (Intel)])!
  INFO root [2019-10-01 16:50:17,763] - Script::install(): KBExtra is successfully!
S_INFO root [2019-10-01 16:50:17,778] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2019-10-01 16:50:17,779] - TelnetServer server is running on port 31000
  INFO root [2019-10-01 16:50:18,251] - ---- loginapp is running ----
 DEBUG root [2019-10-01 16:50:18,252] - Components::process(): Request for the process of identity...
  WARN root [2019-10-01 16:50:24,397] - Forwarding logs to logger[10.12.231.110:53884/0/0/0]...
 ERROR root [2019-10-01 16:51:42,590] - Components::removeComponentByChannel: logger : 2000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=94947721532, lastReceivedTime=94930295890, inactivityExceptionPeriod=599499617)
  INFO root [2019-10-01 16:51:42,590] - The following logs sent to logger failed:
  WARN root [2019-10-01 16:51:42,590] - ==> [2019-10-01 16:51:42 593] TCPPacketReceiver::processPendingEvents(10.12.231.110:53884): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2019-10-01 16:51:42,590] - ==> [2019-10-01 16:51:42 594] Components::removeComponentByChannel: logger : 2000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=94947721532, lastReceivedTime=94930295890, inactivityExceptionPeriod=599499617)
  WARN root [2019-10-01 16:51:42,669] - TCPPacketReceiver::processPendingEvents(10.12.231.110:53885): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2019-10-01 16:51:42,669] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=94948558446, lastReceivedTime=94931696408, inactivityExceptionPeriod=599499617)
  INFO root [2019-10-01 16:51:42,685] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [2019-10-01 16:51:42,685] - onLoginAppShutDown()
  INFO root [2019-10-01 16:51:42,685] - Shutdowner::onShutdown: shutting down
  INFO root [2019-10-01 16:51:42,690] - Shutdowner::onShutdownEnd: shutting down
  INFO root [2019-10-01 16:51:42,695] - Script::uninstall(): is successfully!
 DEBUG root [2019-10-01 16:51:42,695] - ThreadPool::destroy(): starting size 2.
  WARN root [2019-10-01 16:51:43,000] - ThreadPool::destroy(): waiting for thread(2)[0x1528ce0,0x1528f50,], try=1
  INFO root [2019-10-01 16:55:06,475] - 
  INFO root [2019-10-01 16:55:06,476] - -----------------------------------------------------------------------------------------


  INFO root [2019-10-01 16:55:06,477] - Resmgr::initialize: KBE_ROOT=D:/kbengine/
  INFO root [2019-10-01 16:55:06,477] - Resmgr::initialize: KBE_RES_PATH=D:/kbengine/kbe/res/;D:/kbengine/BattleOfBalls_assets/;D:/kbengine/BattleOfBalls_assets/scripts/;D:/kbengine/BattleOfBalls_assets/res/
  INFO root [2019-10-01 16:55:06,477] - Resmgr::initialize: KBE_BIN_PATH=D:/kbengine/kbe/bin/server/
  INFO root [2019-10-01 16:55:06,507] - NetworkInterface::initialize(EXTERNAL-TCP): bound to all interfaces with default route interface on 10.12.231.110 ( 10.12.231.110:20013 )
  INFO root [2019-10-01 16:55:06,511] - NetworkInterface::initialize(EXTERNAL-TCP): address 10.12.231.110:20013, SOMAXCONN=128.
  INFO root [2019-10-01 16:55:06,514] - NetworkInterface::initialize(INTERNAL-TCP): bound to all interfaces with default route interface on 10.12.231.110 ( 10.12.231.110:54005 )
  INFO root [2019-10-01 16:55:06,515] - NetworkInterface::initialize(INTERNAL-TCP): address 10.12.231.110:54005, SOMAXCONN=128.
  INFO root [2019-10-01 16:55:06,515] - server-configs:
  INFO root [2019-10-01 16:55:06,515] - 	internalTcpAddr : 10.12.231.110:54005
  INFO root [2019-10-01 16:55:06,515] - 	externalTcpAddr : 10.12.231.110:20013
  INFO root [2019-10-01 16:55:06,515] - 	componentID : 9000
  WARN root [2019-10-01 16:55:06,694] - invalid UID(0) <= 0, please check UID for environment! automatically set to 41181.
  INFO root [2019-10-01 16:55:06,704] - Components::findLogger: found logger, addr:10.12.231.110:53999
  INFO root [2019-10-01 16:55:06,704] - Components::addComponent: reset orderLog, uid=41181!
  INFO root [2019-10-01 16:55:06,705] - Components::addComponent[logger], uid=41181, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2019-10-01 16:55:06,710] - ---- loginapp Version: 2.4.5. ScriptVersion: 0.1.0. Pythoncore: 3.7.3. Protocol: CE9FF53F4E85387EE4455C7191269324. Config: Debug X86. Built: 09:58:16 May  8 2019. AppID: 9000. UID: 41181. PID: 8700 ----
  INFO root [2019-10-01 16:55:06,710] - Server error_name: Intel(R) Core(TM) i5-6300HQ CPU @ 2.30GHz with 2097151kB RAM
  INFO root [2019-10-01 16:55:06,710] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2019-10-01 16:55:06,711] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
  INFO root [2019-10-01 16:55:07,110] - Script::install(): is successfully, Python=(3.7.3 (default, May  8 2019, 09:53:38) [MSC v.1916 32 bit (Intel)])!
  INFO root [2019-10-01 16:55:07,110] - Script::install(): KBExtra is successfully!
S_INFO root [2019-10-01 16:55:07,128] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2019-10-01 16:55:07,128] - TelnetServer server is running on port 31000
  INFO root [2019-10-01 16:55:07,609] - ---- loginapp is running ----
 DEBUG root [2019-10-01 16:55:07,609] - Components::process(): Request for the process of identity...
  WARN root [2019-10-01 16:55:13,735] - Forwarding logs to logger[10.12.231.110:53999/0/0/0]...
 ERROR root [2019-10-01 16:56:56,594] - Components::removeComponentByChannel: logger : 2000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=98087724306, lastReceivedTime=97881947719, inactivityExceptionPeriod=599500000)
  INFO root [2019-10-01 16:56:56,596] - The following logs sent to logger failed:
  WARN root [2019-10-01 16:56:56,596] - ==> [2019-10-01 16:56:56 594] TCPPacketReceiver::processPendingEvents(10.12.231.110:53999): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2019-10-01 16:56:56,596] - ==> [2019-10-01 16:56:56 594] Components::removeComponentByChannel: logger : 2000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=98087724306, lastReceivedTime=97881947719, inactivityExceptionPeriod=599500000)
  WARN root [2019-10-01 16:56:56,662] - TCPPacketReceiver::processPendingEvents(10.12.231.110:54000): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2019-10-01 16:56:56,663] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=98088414989, lastReceivedTime=97883576735, inactivityExceptionPeriod=599500000)
  INFO root [2019-10-01 16:56:56,670] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [2019-10-01 16:56:56,671] - onLoginAppShutDown()
  INFO root [2019-10-01 16:56:56,672] - Shutdowner::onShutdown: shutting down
  INFO root [2019-10-01 16:56:56,672] - Shutdowner::onShutdownEnd: shutting down
  INFO root [2019-10-01 16:56:56,682] - Script::uninstall(): is successfully!
 DEBUG root [2019-10-01 16:56:56,683] - ThreadPool::destroy(): starting size 2.
  WARN root [2019-10-01 16:56:56,983] - ThreadPool::destroy(): waiting for thread(2)[0x16e7040,0x16e74b8,], try=1
  INFO root [2019-10-01 16:58:25,704] - 
  INFO root [2019-10-01 16:58:25,705] - -----------------------------------------------------------------------------------------


  INFO root [2019-10-01 16:58:25,706] - Resmgr::initialize: KBE_ROOT=D:/kbengine/
  INFO root [2019-10-01 16:58:25,706] - Resmgr::initialize: KBE_RES_PATH=D:/kbengine/kbe/res/;D:/kbengine/BattleOfBalls_assets/;D:/kbengine/BattleOfBalls_assets/scripts/;D:/kbengine/BattleOfBalls_assets/res/
  INFO root [2019-10-01 16:58:25,706] - Resmgr::initialize: KBE_BIN_PATH=D:/kbengine/kbe/bin/server/
  INFO root [2019-10-01 16:58:25,741] - NetworkInterface::initialize(EXTERNAL-TCP): bound to all interfaces with default route interface on 10.12.231.110 ( 10.12.231.110:20013 )
  INFO root [2019-10-01 16:58:25,741] - NetworkInterface::initialize(EXTERNAL-TCP): address 10.12.231.110:20013, SOMAXCONN=128.
  INFO root [2019-10-01 16:58:25,745] - NetworkInterface::initialize(INTERNAL-TCP): bound to all interfaces with default route interface on 10.12.231.110 ( 10.12.231.110:54089 )
  INFO root [2019-10-01 16:58:25,745] - NetworkInterface::initialize(INTERNAL-TCP): address 10.12.231.110:54089, SOMAXCONN=128.
  INFO root [2019-10-01 16:58:25,745] - server-configs:
  INFO root [2019-10-01 16:58:25,745] - 	internalTcpAddr : 10.12.231.110:54089
  INFO root [2019-10-01 16:58:25,745] - 	externalTcpAddr : 10.12.231.110:20013
  INFO root [2019-10-01 16:58:25,746] - 	componentID : 9000
  WARN root [2019-10-01 16:58:25,916] - invalid UID(0) <= 0, please check UID for environment! automatically set to 41181.
  INFO root [2019-10-01 16:58:25,943] - Components::findLogger: found logger, addr:10.12.231.110:54083
  INFO root [2019-10-01 16:58:25,944] - Components::addComponent: reset orderLog, uid=41181!
  INFO root [2019-10-01 16:58:25,944] - Components::addComponent[logger], uid=41181, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2019-10-01 16:58:31,859] - ---- loginapp Version: 2.4.5. ScriptVersion: 0.1.0. Pythoncore: 3.7.3. Protocol: CE9FF53F4E85387EE4455C7191269324. Config: Debug X86. Built: 09:58:16 May  8 2019. AppID: 9000. UID: 41181. PID: 5328 ----
  INFO root [2019-10-01 16:58:31,860] - Server error_name: Intel(R) Core(TM) i5-6300HQ CPU @ 2.30GHz with 2097151kB RAM
  INFO root [2019-10-01 16:58:31,860] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2019-10-01 16:58:31,861] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
  INFO root [2019-10-01 16:58:32,060] - Script::install(): is successfully, Python=(3.7.3 (default, May  8 2019, 09:53:38) [MSC v.1916 32 bit (Intel)])!
  INFO root [2019-10-01 16:58:32,060] - Script::install(): KBExtra is successfully!
S_INFO root [2019-10-01 16:58:32,072] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2019-10-01 16:58:32,072] - TelnetServer server is running on port 31000
  INFO root [2019-10-01 16:58:32,475] - ---- loginapp is running ----
 DEBUG root [2019-10-01 16:58:32,475] - Components::process(): Request for the process of identity...
  WARN root [2019-10-01 16:58:38,615] - Forwarding logs to logger[10.12.231.110:54083/0/0/0]...
 ERROR root [2019-10-01 17:00:23,965] - Components::removeComponentByChannel: logger : 2000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=100161443058, lastReceivedTime=99874407471, inactivityExceptionPeriod=599500064)
  INFO root [2019-10-01 17:00:23,969] - The following logs sent to logger failed:
  WARN root [2019-10-01 17:00:23,969] - ==> [2019-10-01 17:00:23 964] TCPPacketReceiver::processPendingEvents(10.12.231.110:54083): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2019-10-01 17:00:23,970] - ==> [2019-10-01 17:00:23 966] Components::removeComponentByChannel: logger : 2000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=100161443058, lastReceivedTime=99874407471, inactivityExceptionPeriod=599500064)
  WARN root [2019-10-01 17:00:24,036] - TCPPacketReceiver::processPendingEvents(10.12.231.110:54084): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2019-10-01 17:00:24,038] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=100162166893, lastReceivedTime=99875829359, inactivityExceptionPeriod=599500064)
  INFO root [2019-10-01 17:00:24,042] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [2019-10-01 17:00:24,044] - onLoginAppShutDown()
  INFO root [2019-10-01 17:00:24,044] - Shutdowner::onShutdown: shutting down
  INFO root [2019-10-01 17:00:24,044] - Shutdowner::onShutdownEnd: shutting down
  INFO root [2019-10-01 17:00:24,054] - Script::uninstall(): is successfully!
 DEBUG root [2019-10-01 17:00:24,054] - ThreadPool::destroy(): starting size 2.
  WARN root [2019-10-01 17:00:24,355] - ThreadPool::destroy(): waiting for thread(2)[0x1759508,0x1759f98,], try=1
  INFO root [2019-10-01 17:02:51,405] - 
  INFO root [2019-10-01 17:02:51,406] - -----------------------------------------------------------------------------------------


  INFO root [2019-10-01 17:02:51,407] - Resmgr::initialize: KBE_ROOT=D:/kbengine/
  INFO root [2019-10-01 17:02:51,407] - Resmgr::initialize: KBE_RES_PATH=D:/kbengine/kbe/res/;D:/kbengine/BattleOfBalls_assets/;D:/kbengine/BattleOfBalls_assets/scripts/;D:/kbengine/BattleOfBalls_assets/res/
  INFO root [2019-10-01 17:02:51,407] - Resmgr::initialize: KBE_BIN_PATH=D:/kbengine/kbe/bin/server/
  INFO root [2019-10-01 17:02:51,416] - NetworkInterface::initialize(EXTERNAL-TCP): bound to all interfaces with default route interface on 10.12.231.110 ( 10.12.231.110:20013 )
  INFO root [2019-10-01 17:02:51,417] - NetworkInterface::initialize(EXTERNAL-TCP): address 10.12.231.110:20013, SOMAXCONN=128.
  INFO root [2019-10-01 17:02:51,422] - NetworkInterface::initialize(INTERNAL-TCP): bound to all interfaces with default route interface on 10.12.231.110 ( 10.12.231.110:54184 )
  INFO root [2019-10-01 17:02:51,423] - NetworkInterface::initialize(INTERNAL-TCP): address 10.12.231.110:54184, SOMAXCONN=128.
  INFO root [2019-10-01 17:02:51,423] - server-configs:
  INFO root [2019-10-01 17:02:51,423] - 	internalTcpAddr : 10.12.231.110:54184
  INFO root [2019-10-01 17:02:51,423] - 	externalTcpAddr : 10.12.231.110:20013
  INFO root [2019-10-01 17:02:51,423] - 	componentID : 9000
  WARN root [2019-10-01 17:02:51,579] - invalid UID(0) <= 0, please check UID for environment! automatically set to 41181.
  INFO root [2019-10-01 17:02:51,590] - Components::findLogger: found logger, addr:10.12.231.110:54175
  INFO root [2019-10-01 17:02:51,590] - Components::addComponent: reset orderLog, uid=41181!
  INFO root [2019-10-01 17:02:51,590] - Components::addComponent[logger], uid=41181, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2019-10-01 17:02:57,503] - ---- loginapp Version: 2.4.5. ScriptVersion: 0.1.0. Pythoncore: 3.7.3. Protocol: CE9FF53F4E85387EE4455C7191269324. Config: Debug X86. Built: 09:58:16 May  8 2019. AppID: 9000. UID: 41181. PID: 8488 ----
  INFO root [2019-10-01 17:02:57,504] - Server error_name: Intel(R) Core(TM) i5-6300HQ CPU @ 2.30GHz with 2097151kB RAM
  INFO root [2019-10-01 17:02:57,504] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2019-10-01 17:02:57,505] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
  INFO root [2019-10-01 17:02:57,696] - Script::install(): is successfully, Python=(3.7.3 (default, May  8 2019, 09:53:38) [MSC v.1916 32 bit (Intel)])!
  INFO root [2019-10-01 17:02:57,696] - Script::install(): KBExtra is successfully!
S_INFO root [2019-10-01 17:02:57,707] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2019-10-01 17:02:57,708] - TelnetServer server is running on port 31000
  INFO root [2019-10-01 17:02:58,103] - ---- loginapp is running ----
 DEBUG root [2019-10-01 17:02:58,103] - Components::process(): Request for the process of identity...
  WARN root [2019-10-01 17:03:04,230] - Forwarding logs to logger[10.12.231.110:54175/0/0/0]...
 ERROR root [2019-10-01 17:06:35,970] - Components::removeComponentByChannel: logger : 2000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=103881494798, lastReceivedTime=103730552879, inactivityExceptionPeriod=599499873)
  INFO root [2019-10-01 17:06:35,976] - The following logs sent to logger failed:
  WARN root [2019-10-01 17:06:35,977] - ==> [2019-10-01 17:06:35 969] TCPPacketReceiver::processPendingEvents(10.12.231.110:54175): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2019-10-01 17:06:35,977] - ==> [2019-10-01 17:06:35 972] Components::removeComponentByChannel: logger : 2000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=103881494798, lastReceivedTime=103730552879, inactivityExceptionPeriod=599499873)
  WARN root [2019-10-01 17:06:36,056] - TCPPacketReceiver::processPendingEvents(10.12.231.110:54176): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2019-10-01 17:06:36,057] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=103882361687, lastReceivedTime=103732374466, inactivityExceptionPeriod=599499873)
  INFO root [2019-10-01 17:06:36,063] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [2019-10-01 17:06:36,064] - onLoginAppShutDown()
  INFO root [2019-10-01 17:06:36,065] - Shutdowner::onShutdown: shutting down
  INFO root [2019-10-01 17:06:36,065] - Shutdowner::onShutdownEnd: shutting down
  INFO root [2019-10-01 17:06:36,075] - Script::uninstall(): is successfully!
 DEBUG root [2019-10-01 17:06:36,076] - ThreadPool::destroy(): starting size 2.
  WARN root [2019-10-01 17:06:36,377] - ThreadPool::destroy(): waiting for thread(2)[0x1428350,0x1428690,], try=1
  INFO root [2019-10-01 17:08:32,254] - 
  INFO root [2019-10-01 17:08:32,256] - -----------------------------------------------------------------------------------------


  INFO root [2019-10-01 17:08:32,257] - Resmgr::initialize: KBE_ROOT=D:/kbengine/
  INFO root [2019-10-01 17:08:32,257] - Resmgr::initialize: KBE_RES_PATH=D:/kbengine/kbe/res/;D:/kbengine/BattleOfBalls_assets/;D:/kbengine/BattleOfBalls_assets/scripts/;D:/kbengine/BattleOfBalls_assets/res/
  INFO root [2019-10-01 17:08:32,257] - Resmgr::initialize: KBE_BIN_PATH=D:/kbengine/kbe/bin/server/
  INFO root [2019-10-01 17:08:32,279] - NetworkInterface::initialize(EXTERNAL-TCP): bound to all interfaces with default route interface on 10.12.231.110 ( 10.12.231.110:20013 )
  INFO root [2019-10-01 17:08:32,279] - NetworkInterface::initialize(EXTERNAL-TCP): address 10.12.231.110:20013, SOMAXCONN=128.
  INFO root [2019-10-01 17:08:32,283] - NetworkInterface::initialize(INTERNAL-TCP): bound to all interfaces with default route interface on 10.12.231.110 ( 10.12.231.110:54282 )
  INFO root [2019-10-01 17:08:32,283] - NetworkInterface::initialize(INTERNAL-TCP): address 10.12.231.110:54282, SOMAXCONN=128.
  INFO root [2019-10-01 17:08:32,283] - server-configs:
  INFO root [2019-10-01 17:08:32,283] - 	internalTcpAddr : 10.12.231.110:54282
  INFO root [2019-10-01 17:08:32,283] - 	externalTcpAddr : 10.12.231.110:20013
  INFO root [2019-10-01 17:08:32,283] - 	componentID : 9000
  WARN root [2019-10-01 17:08:32,462] - invalid UID(0) <= 0, please check UID for environment! automatically set to 41181.
  INFO root [2019-10-01 17:08:32,482] - Components::findLogger: found logger, addr:10.12.231.110:54272
  INFO root [2019-10-01 17:08:32,482] - Components::addComponent: reset orderLog, uid=41181!
  INFO root [2019-10-01 17:08:32,482] - Components::addComponent[logger], uid=41181, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2019-10-01 17:08:38,401] - ---- loginapp Version: 2.4.5. ScriptVersion: 0.1.0. Pythoncore: 3.7.3. Protocol: CE9FF53F4E85387EE4455C7191269324. Config: Debug X86. Built: 09:58:16 May  8 2019. AppID: 9000. UID: 41181. PID: 11388 ----
  INFO root [2019-10-01 17:08:38,402] - Server error_name: Intel(R) Core(TM) i5-6300HQ CPU @ 2.30GHz with 2097151kB RAM
  INFO root [2019-10-01 17:08:38,402] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2019-10-01 17:08:38,403] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
  INFO root [2019-10-01 17:08:38,603] - Script::install(): is successfully, Python=(3.7.3 (default, May  8 2019, 09:53:38) [MSC v.1916 32 bit (Intel)])!
  INFO root [2019-10-01 17:08:38,603] - Script::install(): KBExtra is successfully!
S_INFO root [2019-10-01 17:08:38,614] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2019-10-01 17:08:38,615] - TelnetServer server is running on port 31000
  INFO root [2019-10-01 17:08:39,012] - ---- loginapp is running ----
 DEBUG root [2019-10-01 17:08:39,013] - Components::process(): Request for the process of identity...
  WARN root [2019-10-01 17:08:45,148] - Forwarding logs to logger[10.12.231.110:54272/0/0/0]...
 ERROR root [2019-10-01 17:09:01,672] - Components::removeComponentByChannel: logger : 2000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=105338508583, lastReceivedTime=105105737399, inactivityExceptionPeriod=599498913)
  INFO root [2019-10-01 17:09:01,674] - The following logs sent to logger failed:
  WARN root [2019-10-01 17:09:01,674] - ==> [2019-10-01 17:09:01 668] TCPPacketReceiver::processPendingEvents(10.12.231.110:54272): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2019-10-01 17:09:01,675] - ==> [2019-10-01 17:09:01 673] Components::removeComponentByChannel: logger : 2000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=105338508583, lastReceivedTime=105105737399, inactivityExceptionPeriod=599498913)
  WARN root [2019-10-01 17:09:01,761] - TCPPacketReceiver::processPendingEvents(10.12.231.110:54273): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2019-10-01 17:09:01,762] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=105339414409, lastReceivedTime=105254995145, inactivityExceptionPeriod=599498913)
  INFO root [2019-10-01 17:09:01,781] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [2019-10-01 17:09:01,782] - onLoginAppShutDown()
  INFO root [2019-10-01 17:09:01,782] - Shutdowner::onShutdown: shutting down
  INFO root [2019-10-01 17:09:01,782] - Shutdowner::onShutdownEnd: shutting down
  INFO root [2019-10-01 17:09:01,794] - Script::uninstall(): is successfully!
 DEBUG root [2019-10-01 17:09:01,795] - ThreadPool::destroy(): starting size 2.
  WARN root [2019-10-01 17:09:02,096] - ThreadPool::destroy(): waiting for thread(2)[0x1438970,0x1438be0,], try=1
  INFO root [2019-10-01 17:09:03,810] - 
  INFO root [2019-10-01 17:09:03,810] - -----------------------------------------------------------------------------------------


  INFO root [2019-10-01 17:09:03,811] - Resmgr::initialize: KBE_ROOT=D:/kbengine/
  INFO root [2019-10-01 17:09:03,811] - Resmgr::initialize: KBE_RES_PATH=D:/kbengine/kbe/res/;D:/kbengine/BattleOfBalls_assets/;D:/kbengine/BattleOfBalls_assets/scripts/;D:/kbengine/BattleOfBalls_assets/res/
  INFO root [2019-10-01 17:09:03,811] - Resmgr::initialize: KBE_BIN_PATH=D:/kbengine/kbe/bin/server/
  INFO root [2019-10-01 17:09:03,826] - NetworkInterface::initialize(EXTERNAL-TCP): bound to all interfaces with default route interface on 10.12.231.110 ( 10.12.231.110:20013 )
  INFO root [2019-10-01 17:09:03,826] - NetworkInterface::initialize(EXTERNAL-TCP): address 10.12.231.110:20013, SOMAXCONN=128.
  INFO root [2019-10-01 17:09:03,830] - NetworkInterface::initialize(INTERNAL-TCP): bound to all interfaces with default route interface on 10.12.231.110 ( 10.12.231.110:54315 )
  INFO root [2019-10-01 17:09:03,830] - NetworkInterface::initialize(INTERNAL-TCP): address 10.12.231.110:54315, SOMAXCONN=128.
  INFO root [2019-10-01 17:09:03,830] - server-configs:
  INFO root [2019-10-01 17:09:03,830] - 	internalTcpAddr : 10.12.231.110:54315
  INFO root [2019-10-01 17:09:03,830] - 	externalTcpAddr : 10.12.231.110:20013
  INFO root [2019-10-01 17:09:03,830] - 	componentID : 9000
  WARN root [2019-10-01 17:09:04,053] - invalid UID(0) <= 0, please check UID for environment! automatically set to 41181.
  INFO root [2019-10-01 17:09:04,153] - Components::findLogger: found logger, addr:10.12.231.110:54309
  INFO root [2019-10-01 17:09:04,153] - Components::addComponent: reset orderLog, uid=41181!
  INFO root [2019-10-01 17:09:04,154] - Components::addComponent[logger], uid=41181, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2019-10-01 17:09:04,159] - ---- loginapp Version: 2.4.5. ScriptVersion: 0.1.0. Pythoncore: 3.7.3. Protocol: CE9FF53F4E85387EE4455C7191269324. Config: Debug X86. Built: 09:58:16 May  8 2019. AppID: 9000. UID: 41181. PID: 12836 ----
  INFO root [2019-10-01 17:09:04,159] - Server error_name: Intel(R) Core(TM) i5-6300HQ CPU @ 2.30GHz with 2097151kB RAM
  INFO root [2019-10-01 17:09:04,159] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2019-10-01 17:09:04,160] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
  INFO root [2019-10-01 17:09:04,396] - Script::install(): is successfully, Python=(3.7.3 (default, May  8 2019, 09:53:38) [MSC v.1916 32 bit (Intel)])!
  INFO root [2019-10-01 17:09:04,396] - Script::install(): KBExtra is successfully!
S_INFO root [2019-10-01 17:09:04,408] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2019-10-01 17:09:04,408] - TelnetServer server is running on port 31000
  INFO root [2019-10-01 17:09:04,841] - ---- loginapp is running ----
 DEBUG root [2019-10-01 17:09:04,841] - Components::process(): Request for the process of identity...
  WARN root [2019-10-01 17:09:10,966] - Forwarding logs to logger[10.12.231.110:54309/0/0/0]...
 ERROR root [2019-10-01 17:14:20,745] - Components::removeComponentByChannel: logger : 2000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=108529237690, lastReceivedTime=108356153503, inactivityExceptionPeriod=599498913)
  INFO root [2019-10-01 17:14:20,749] - The following logs sent to logger failed:
  WARN root [2019-10-01 17:14:20,749] - ==> [2019-10-01 17:14:20 744] TCPPacketReceiver::processPendingEvents(10.12.231.110:54309): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2019-10-01 17:14:20,749] - ==> [2019-10-01 17:14:20 746] Components::removeComponentByChannel: logger : 2000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=108529237690, lastReceivedTime=108356153503, inactivityExceptionPeriod=599498913)
  WARN root [2019-10-01 17:14:20,816] - TCPPacketReceiver::processPendingEvents(10.12.231.110:54312): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2019-10-01 17:14:20,816] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=108529950857, lastReceivedTime=108359203841, inactivityExceptionPeriod=599498913)
  INFO root [2019-10-01 17:14:20,820] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [2019-10-01 17:14:20,822] - onLoginAppShutDown()
  INFO root [2019-10-01 17:14:20,822] - Shutdowner::onShutdown: shutting down
  INFO root [2019-10-01 17:14:20,823] - Shutdowner::onShutdownEnd: shutting down
  INFO root [2019-10-01 17:14:20,832] - Script::uninstall(): is successfully!
 DEBUG root [2019-10-01 17:14:20,832] - ThreadPool::destroy(): starting size 2.
  WARN root [2019-10-01 17:14:21,132] - ThreadPool::destroy(): waiting for thread(2)[0x16ca9e8,0x16cacc0,], try=1
  INFO root [2019-10-01 17:15:33,504] - 
  INFO root [2019-10-01 17:15:33,506] - -----------------------------------------------------------------------------------------


  INFO root [2019-10-01 17:15:33,507] - Resmgr::initialize: KBE_ROOT=D:/kbengine/
  INFO root [2019-10-01 17:15:33,507] - Resmgr::initialize: KBE_RES_PATH=D:/kbengine/kbe/res/;D:/kbengine/BattleOfBalls_assets/;D:/kbengine/BattleOfBalls_assets/scripts/;D:/kbengine/BattleOfBalls_assets/res/
  INFO root [2019-10-01 17:15:33,507] - Resmgr::initialize: KBE_BIN_PATH=D:/kbengine/kbe/bin/server/
  INFO root [2019-10-01 17:15:33,523] - NetworkInterface::initialize(EXTERNAL-TCP): bound to all interfaces with default route interface on 10.12.231.110 ( 10.12.231.110:20013 )
  INFO root [2019-10-01 17:15:33,524] - NetworkInterface::initialize(EXTERNAL-TCP): address 10.12.231.110:20013, SOMAXCONN=128.
  INFO root [2019-10-01 17:15:33,528] - NetworkInterface::initialize(INTERNAL-TCP): bound to all interfaces with default route interface on 10.12.231.110 ( 10.12.231.110:54403 )
  INFO root [2019-10-01 17:15:33,528] - NetworkInterface::initialize(INTERNAL-TCP): address 10.12.231.110:54403, SOMAXCONN=128.
  INFO root [2019-10-01 17:15:33,528] - server-configs:
  INFO root [2019-10-01 17:15:33,528] - 	internalTcpAddr : 10.12.231.110:54403
  INFO root [2019-10-01 17:15:33,528] - 	externalTcpAddr : 10.12.231.110:20013
  INFO root [2019-10-01 17:15:33,528] - 	componentID : 9000
  WARN root [2019-10-01 17:15:33,688] - invalid UID(0) <= 0, please check UID for environment! automatically set to 41181.
  INFO root [2019-10-01 17:15:33,786] - Components::findLogger: found logger, addr:10.12.231.110:54397
  INFO root [2019-10-01 17:15:33,786] - Components::addComponent: reset orderLog, uid=41181!
  INFO root [2019-10-01 17:15:33,787] - Components::addComponent[logger], uid=41181, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2019-10-01 17:15:39,719] - ---- loginapp Version: 2.4.5. ScriptVersion: 0.1.0. Pythoncore: 3.7.3. Protocol: CE9FF53F4E85387EE4455C7191269324. Config: Debug X86. Built: 09:58:16 May  8 2019. AppID: 9000. UID: 41181. PID: 13092 ----
  INFO root [2019-10-01 17:15:39,720] - Server error_name: Intel(R) Core(TM) i5-6300HQ CPU @ 2.30GHz with 2097151kB RAM
  INFO root [2019-10-01 17:15:39,720] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2019-10-01 17:15:39,721] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
  INFO root [2019-10-01 17:15:39,919] - Script::install(): is successfully, Python=(3.7.3 (default, May  8 2019, 09:53:38) [MSC v.1916 32 bit (Intel)])!
  INFO root [2019-10-01 17:15:39,920] - Script::install(): KBExtra is successfully!
S_INFO root [2019-10-01 17:15:39,933] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2019-10-01 17:15:39,934] - TelnetServer server is running on port 31000
  INFO root [2019-10-01 17:15:40,387] - ---- loginapp is running ----
 DEBUG root [2019-10-01 17:15:40,387] - Components::process(): Request for the process of identity...
  WARN root [2019-10-01 17:15:46,546] - Forwarding logs to logger[10.12.231.110:54397/0/0/0]...
 ERROR root [2019-10-01 17:17:07,093] - Components::removeComponentByChannel: logger : 2000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=110192721631, lastReceivedTime=110152067888, inactivityExceptionPeriod=599500064)
  INFO root [2019-10-01 17:17:07,095] - The following logs sent to logger failed:
  WARN root [2019-10-01 17:17:07,095] - ==> [2019-10-01 17:17:07 090] TCPPacketReceiver::processPendingEvents(10.12.231.110:54397): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2019-10-01 17:17:07,096] - ==> [2019-10-01 17:17:07 094] Components::removeComponentByChannel: logger : 2000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=110192721631, lastReceivedTime=110152067888, inactivityExceptionPeriod=599500064)
  WARN root [2019-10-01 17:17:07,163] - TCPPacketReceiver::processPendingEvents(10.12.231.110:54398): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2019-10-01 17:17:07,166] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=110193448474, lastReceivedTime=110153393481, inactivityExceptionPeriod=599500064)
  INFO root [2019-10-01 17:17:07,173] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [2019-10-01 17:17:07,173] - onLoginAppShutDown()
  INFO root [2019-10-01 17:17:07,173] - Shutdowner::onShutdown: shutting down
  INFO root [2019-10-01 17:17:07,173] - Shutdowner::onShutdownEnd: shutting down
  INFO root [2019-10-01 17:17:07,182] - Script::uninstall(): is successfully!
 DEBUG root [2019-10-01 17:17:07,182] - ThreadPool::destroy(): starting size 2.
  WARN root [2019-10-01 17:17:07,484] - ThreadPool::destroy(): waiting for thread(2)[0x1549930,0x1548f08,], try=1
  INFO root [2019-10-01 17:18:08,164] - 
  INFO root [2019-10-01 17:18:08,165] - -----------------------------------------------------------------------------------------


  INFO root [2019-10-01 17:18:08,166] - Resmgr::initialize: KBE_ROOT=D:/kbengine/
  INFO root [2019-10-01 17:18:08,166] - Resmgr::initialize: KBE_RES_PATH=D:/kbengine/kbe/res/;D:/kbengine/BattleOfBalls_assets/;D:/kbengine/BattleOfBalls_assets/scripts/;D:/kbengine/BattleOfBalls_assets/res/
  INFO root [2019-10-01 17:18:08,166] - Resmgr::initialize: KBE_BIN_PATH=D:/kbengine/kbe/bin/server/
  INFO root [2019-10-01 17:18:08,177] - NetworkInterface::initialize(EXTERNAL-TCP): bound to all interfaces with default route interface on 10.12.231.110 ( 10.12.231.110:20013 )
  INFO root [2019-10-01 17:18:08,177] - NetworkInterface::initialize(EXTERNAL-TCP): address 10.12.231.110:20013, SOMAXCONN=128.
  INFO root [2019-10-01 17:18:08,183] - NetworkInterface::initialize(INTERNAL-TCP): bound to all interfaces with default route interface on 10.12.231.110 ( 10.12.231.110:54465 )
  INFO root [2019-10-01 17:18:08,183] - NetworkInterface::initialize(INTERNAL-TCP): address 10.12.231.110:54465, SOMAXCONN=128.
  INFO root [2019-10-01 17:18:08,183] - server-configs:
  INFO root [2019-10-01 17:18:08,183] - 	internalTcpAddr : 10.12.231.110:54465
  INFO root [2019-10-01 17:18:08,184] - 	externalTcpAddr : 10.12.231.110:20013
  INFO root [2019-10-01 17:18:08,184] - 	componentID : 9000
  WARN root [2019-10-01 17:18:08,344] - invalid UID(0) <= 0, please check UID for environment! automatically set to 41181.
  INFO root [2019-10-01 17:18:08,408] - Components::findLogger: found logger, addr:10.12.231.110:54459
  INFO root [2019-10-01 17:18:08,409] - Components::addComponent: reset orderLog, uid=41181!
  INFO root [2019-10-01 17:18:08,409] - Components::addComponent[logger], uid=41181, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2019-10-01 17:18:14,327] - ---- loginapp Version: 2.4.5. ScriptVersion: 0.1.0. Pythoncore: 3.7.3. Protocol: CE9FF53F4E85387EE4455C7191269324. Config: Debug X86. Built: 09:58:16 May  8 2019. AppID: 9000. UID: 41181. PID: 9292 ----
  INFO root [2019-10-01 17:18:14,327] - Server error_name: Intel(R) Core(TM) i5-6300HQ CPU @ 2.30GHz with 2097151kB RAM
  INFO root [2019-10-01 17:18:14,328] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2019-10-01 17:18:14,328] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
  INFO root [2019-10-01 17:18:14,519] - Script::install(): is successfully, Python=(3.7.3 (default, May  8 2019, 09:53:38) [MSC v.1916 32 bit (Intel)])!
  INFO root [2019-10-01 17:18:14,519] - Script::install(): KBExtra is successfully!
S_INFO root [2019-10-01 17:18:14,530] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2019-10-01 17:18:14,531] - TelnetServer server is running on port 31000
  INFO root [2019-10-01 17:18:14,930] - ---- loginapp is running ----
 DEBUG root [2019-10-01 17:18:14,930] - Components::process(): Request for the process of identity...
  WARN root [2019-10-01 17:18:21,077] - Forwarding logs to logger[10.12.231.110:54459/0/0/0]...
 ERROR root [2019-10-01 17:23:34,298] - Components::removeComponentByChannel: logger : 2000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=114064765322, lastReceivedTime=113798773915, inactivityExceptionPeriod=599500064)
  INFO root [2019-10-01 17:23:34,301] - The following logs sent to logger failed:
  WARN root [2019-10-01 17:23:34,301] - ==> [2019-10-01 17:23:34 297] TCPPacketReceiver::processPendingEvents(10.12.231.110:54459): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2019-10-01 17:23:34,301] - ==> [2019-10-01 17:23:34 299] Components::removeComponentByChannel: logger : 2000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=114064765322, lastReceivedTime=113798773915, inactivityExceptionPeriod=599500064)
  WARN root [2019-10-01 17:23:34,364] - TCPPacketReceiver::processPendingEvents(10.12.231.110:54460): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2019-10-01 17:23:34,365] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=114065436845, lastReceivedTime=113799971059, inactivityExceptionPeriod=599500064)
  INFO root [2019-10-01 17:23:34,375] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [2019-10-01 17:23:34,376] - onLoginAppShutDown()
  INFO root [2019-10-01 17:23:34,377] - Shutdowner::onShutdown: shutting down
  INFO root [2019-10-01 17:23:34,377] - Shutdowner::onShutdownEnd: shutting down
  INFO root [2019-10-01 17:23:34,396] - Script::uninstall(): is successfully!
 DEBUG root [2019-10-01 17:23:34,399] - ThreadPool::destroy(): starting size 2.
  WARN root [2019-10-01 17:23:34,703] - ThreadPool::destroy(): waiting for thread(2)[0x165c3f8,0x165b968,], try=1
  INFO root [2019-10-01 17:23:36,619] - 
  INFO root [2019-10-01 17:23:36,620] - -----------------------------------------------------------------------------------------


  INFO root [2019-10-01 17:23:36,622] - Resmgr::initialize: KBE_ROOT=D:/kbengine/
  INFO root [2019-10-01 17:23:36,622] - Resmgr::initialize: KBE_RES_PATH=D:/kbengine/kbe/res/;D:/kbengine/BattleOfBalls_assets/;D:/kbengine/BattleOfBalls_assets/scripts/;D:/kbengine/BattleOfBalls_assets/res/
  INFO root [2019-10-01 17:23:36,622] - Resmgr::initialize: KBE_BIN_PATH=D:/kbengine/kbe/bin/server/
  INFO root [2019-10-01 17:23:36,634] - NetworkInterface::initialize(EXTERNAL-TCP): bound to all interfaces with default route interface on 10.12.231.110 ( 10.12.231.110:20013 )
  INFO root [2019-10-01 17:23:36,650] - NetworkInterface::initialize(EXTERNAL-TCP): address 10.12.231.110:20013, SOMAXCONN=128.
  INFO root [2019-10-01 17:23:36,654] - NetworkInterface::initialize(INTERNAL-TCP): bound to all interfaces with default route interface on 10.12.231.110 ( 10.12.231.110:54562 )
  INFO root [2019-10-01 17:23:36,654] - NetworkInterface::initialize(INTERNAL-TCP): address 10.12.231.110:54562, SOMAXCONN=128.
  INFO root [2019-10-01 17:23:36,654] - server-configs:
  INFO root [2019-10-01 17:23:36,654] - 	internalTcpAddr : 10.12.231.110:54562
  INFO root [2019-10-01 17:23:36,654] - 	externalTcpAddr : 10.12.231.110:20013
  INFO root [2019-10-01 17:23:36,654] - 	componentID : 9000
  WARN root [2019-10-01 17:23:36,833] - invalid UID(0) <= 0, please check UID for environment! automatically set to 41181.
  INFO root [2019-10-01 17:23:36,880] - Components::findLogger: found logger, addr:10.12.231.110:54556
  INFO root [2019-10-01 17:23:36,880] - Components::addComponent: reset orderLog, uid=41181!
  INFO root [2019-10-01 17:23:36,880] - Components::addComponent[logger], uid=41181, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2019-10-01 17:23:42,795] - ---- loginapp Version: 2.4.5. ScriptVersion: 0.1.0. Pythoncore: 3.7.3. Protocol: CE9FF53F4E85387EE4455C7191269324. Config: Debug X86. Built: 09:58:16 May  8 2019. AppID: 9000. UID: 41181. PID: 12516 ----
  INFO root [2019-10-01 17:23:42,796] - Server error_name: Intel(R) Core(TM) i5-6300HQ CPU @ 2.30GHz with 2097151kB RAM
  INFO root [2019-10-01 17:23:42,796] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2019-10-01 17:23:42,797] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
  INFO root [2019-10-01 17:23:43,012] - Script::install(): is successfully, Python=(3.7.3 (default, May  8 2019, 09:53:38) [MSC v.1916 32 bit (Intel)])!
  INFO root [2019-10-01 17:23:43,012] - Script::install(): KBExtra is successfully!
S_INFO root [2019-10-01 17:23:43,024] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2019-10-01 17:23:43,024] - TelnetServer server is running on port 31000
  INFO root [2019-10-01 17:23:43,502] - ---- loginapp is running ----
 DEBUG root [2019-10-01 17:23:43,503] - Components::process(): Request for the process of identity...
  WARN root [2019-10-01 17:23:49,661] - Forwarding logs to logger[10.12.231.110:54556/0/0/0]...
 ERROR root [2019-10-01 17:25:28,805] - Components::removeComponentByChannel: logger : 2000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=115209837711, lastReceivedTime=114983502736, inactivityExceptionPeriod=599500000)
  INFO root [2019-10-01 17:25:28,808] - The following logs sent to logger failed:
  WARN root [2019-10-01 17:25:28,808] - ==> [2019-10-01 17:25:28 801] TCPPacketReceiver::processPendingEvents(10.12.231.110:54556): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2019-10-01 17:25:28,808] - ==> [2019-10-01 17:25:28 806] Components::removeComponentByChannel: logger : 2000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=115209837711, lastReceivedTime=114983502736, inactivityExceptionPeriod=599500000)
  WARN root [2019-10-01 17:25:28,883] - TCPPacketReceiver::processPendingEvents(10.12.231.110:54558): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2019-10-01 17:25:28,884] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=115210630411, lastReceivedTime=114985221997, inactivityExceptionPeriod=599500000)
  INFO root [2019-10-01 17:25:28,889] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [2019-10-01 17:25:28,890] - onLoginAppShutDown()
  INFO root [2019-10-01 17:25:28,891] - Shutdowner::onShutdown: shutting down
  INFO root [2019-10-01 17:25:28,891] - Shutdowner::onShutdownEnd: shutting down
  INFO root [2019-10-01 17:25:28,901] - Script::uninstall(): is successfully!
 DEBUG root [2019-10-01 17:25:28,901] - ThreadPool::destroy(): starting size 2.
  WARN root [2019-10-01 17:25:29,202] - ThreadPool::destroy(): waiting for thread(2)[0x144a398,0x144a670,], try=1
  INFO root [2019-10-01 17:26:26,023] - 
  INFO root [2019-10-01 17:26:26,024] - -----------------------------------------------------------------------------------------


  INFO root [2019-10-01 17:26:26,026] - Resmgr::initialize: KBE_ROOT=D:/kbengine/
  INFO root [2019-10-01 17:26:26,026] - Resmgr::initialize: KBE_RES_PATH=D:/kbengine/kbe/res/;D:/kbengine/BattleOfBalls_assets/;D:/kbengine/BattleOfBalls_assets/scripts/;D:/kbengine/BattleOfBalls_assets/res/
  INFO root [2019-10-01 17:26:26,026] - Resmgr::initialize: KBE_BIN_PATH=D:/kbengine/kbe/bin/server/
  INFO root [2019-10-01 17:26:26,058] - NetworkInterface::initialize(EXTERNAL-TCP): bound to all interfaces with default route interface on 10.12.231.110 ( 10.12.231.110:20013 )
  INFO root [2019-10-01 17:26:26,058] - NetworkInterface::initialize(EXTERNAL-TCP): address 10.12.231.110:20013, SOMAXCONN=128.
  INFO root [2019-10-01 17:26:26,062] - NetworkInterface::initialize(INTERNAL-TCP): bound to all interfaces with default route interface on 10.12.231.110 ( 10.12.231.110:54644 )
  INFO root [2019-10-01 17:26:26,062] - NetworkInterface::initialize(INTERNAL-TCP): address 10.12.231.110:54644, SOMAXCONN=128.
  INFO root [2019-10-01 17:26:26,062] - server-configs:
  INFO root [2019-10-01 17:26:26,062] - 	internalTcpAddr : 10.12.231.110:54644
  INFO root [2019-10-01 17:26:26,062] - 	externalTcpAddr : 10.12.231.110:20013
  INFO root [2019-10-01 17:26:26,062] - 	componentID : 9000
  WARN root [2019-10-01 17:26:26,247] - invalid UID(0) <= 0, please check UID for environment! automatically set to 41181.
  INFO root [2019-10-01 17:26:26,251] - Components::findLogger: found logger, addr:10.12.231.110:54635
  INFO root [2019-10-01 17:26:26,251] - Components::addComponent: reset orderLog, uid=41181!
  INFO root [2019-10-01 17:26:26,251] - Components::addComponent[logger], uid=41181, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2019-10-01 17:26:32,175] - ---- loginapp Version: 2.4.5. ScriptVersion: 0.1.0. Pythoncore: 3.7.3. Protocol: CE9FF53F4E85387EE4455C7191269324. Config: Debug X86. Built: 09:58:16 May  8 2019. AppID: 9000. UID: 41181. PID: 5960 ----
  INFO root [2019-10-01 17:26:32,177] - Server error_name: Intel(R) Core(TM) i5-6300HQ CPU @ 2.30GHz with 2097151kB RAM
  INFO root [2019-10-01 17:26:32,177] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2019-10-01 17:26:32,178] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
  INFO root [2019-10-01 17:26:32,430] - Script::install(): is successfully, Python=(3.7.3 (default, May  8 2019, 09:53:38) [MSC v.1916 32 bit (Intel)])!
  INFO root [2019-10-01 17:26:32,430] - Script::install(): KBExtra is successfully!
S_INFO root [2019-10-01 17:26:32,447] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2019-10-01 17:26:32,447] - TelnetServer server is running on port 31000
  INFO root [2019-10-01 17:26:32,997] - ---- loginapp is running ----
 DEBUG root [2019-10-01 17:26:32,998] - Components::process(): Request for the process of identity...
  WARN root [2019-10-01 17:26:39,195] - Forwarding logs to logger[10.12.231.110:54635/0/0/0]...
 ERROR root [2019-10-01 17:27:59,625] - Components::removeComponentByChannel: logger : 2000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=116718036803, lastReceivedTime=116676257325, inactivityExceptionPeriod=599484078)
  INFO root [2019-10-01 17:27:59,628] - The following logs sent to logger failed:
  WARN root [2019-10-01 17:27:59,628] - ==> [2019-10-01 17:27:59 619] TCPPacketReceiver::processPendingEvents(10.12.231.110:54635): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2019-10-01 17:27:59,628] - ==> [2019-10-01 17:27:59 626] Components::removeComponentByChannel: logger : 2000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=116718036803, lastReceivedTime=116676257325, inactivityExceptionPeriod=599484078)
  WARN root [2019-10-01 17:27:59,699] - TCPPacketReceiver::processPendingEvents(10.12.231.110:54636): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2019-10-01 17:27:59,701] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=116718798145, lastReceivedTime=116679086063, inactivityExceptionPeriod=599484078)
  INFO root [2019-10-01 17:27:59,705] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [2019-10-01 17:27:59,706] - onLoginAppShutDown()
  INFO root [2019-10-01 17:27:59,706] - Shutdowner::onShutdown: shutting down
  INFO root [2019-10-01 17:27:59,706] - Shutdowner::onShutdownEnd: shutting down
  INFO root [2019-10-01 17:27:59,717] - Script::uninstall(): is successfully!
 DEBUG root [2019-10-01 17:27:59,717] - ThreadPool::destroy(): starting size 2.
  WARN root [2019-10-01 17:28:00,018] - ThreadPool::destroy(): waiting for thread(2)[0x1675708,0x16758a8,], try=1
  INFO root [2019-10-01 17:28:57,875] - 
  INFO root [2019-10-01 17:28:57,876] - -----------------------------------------------------------------------------------------


  INFO root [2019-10-01 17:28:57,877] - Resmgr::initialize: KBE_ROOT=D:/kbengine/
  INFO root [2019-10-01 17:28:57,877] - Resmgr::initialize: KBE_RES_PATH=D:/kbengine/kbe/res/;D:/kbengine/BattleOfBalls_assets/;D:/kbengine/BattleOfBalls_assets/scripts/;D:/kbengine/BattleOfBalls_assets/res/
  INFO root [2019-10-01 17:28:57,877] - Resmgr::initialize: KBE_BIN_PATH=D:/kbengine/kbe/bin/server/
  INFO root [2019-10-01 17:28:57,907] - NetworkInterface::initialize(EXTERNAL-TCP): bound to all interfaces with default route interface on 10.12.231.110 ( 10.12.231.110:20013 )
  INFO root [2019-10-01 17:28:57,908] - NetworkInterface::initialize(EXTERNAL-TCP): address 10.12.231.110:20013, SOMAXCONN=128.
  INFO root [2019-10-01 17:28:57,911] - NetworkInterface::initialize(INTERNAL-TCP): bound to all interfaces with default route interface on 10.12.231.110 ( 10.12.231.110:54718 )
  INFO root [2019-10-01 17:28:57,912] - NetworkInterface::initialize(INTERNAL-TCP): address 10.12.231.110:54718, SOMAXCONN=128.
  INFO root [2019-10-01 17:28:57,912] - server-configs:
  INFO root [2019-10-01 17:28:57,912] - 	internalTcpAddr : 10.12.231.110:54718
  INFO root [2019-10-01 17:28:57,912] - 	externalTcpAddr : 10.12.231.110:20013
  INFO root [2019-10-01 17:28:57,912] - 	componentID : 9000
  WARN root [2019-10-01 17:28:58,107] - invalid UID(0) <= 0, please check UID for environment! automatically set to 41181.
  INFO root [2019-10-01 17:28:58,117] - Components::findLogger: found logger, addr:10.12.231.110:54713
  INFO root [2019-10-01 17:28:58,117] - Components::addComponent: reset orderLog, uid=41181!
  INFO root [2019-10-01 17:28:58,117] - Components::addComponent[logger], uid=41181, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2019-10-01 17:29:04,048] - ---- loginapp Version: 2.4.5. ScriptVersion: 0.1.0. Pythoncore: 3.7.3. Protocol: CE9FF53F4E85387EE4455C7191269324. Config: Debug X86. Built: 09:58:16 May  8 2019. AppID: 9000. UID: 41181. PID: 1452 ----
  INFO root [2019-10-01 17:29:04,049] - Server error_name: Intel(R) Core(TM) i5-6300HQ CPU @ 2.30GHz with 2097151kB RAM
  INFO root [2019-10-01 17:29:04,049] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2019-10-01 17:29:04,050] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
  INFO root [2019-10-01 17:29:04,266] - Script::install(): is successfully, Python=(3.7.3 (default, May  8 2019, 09:53:38) [MSC v.1916 32 bit (Intel)])!
  INFO root [2019-10-01 17:29:04,266] - Script::install(): KBExtra is successfully!
S_INFO root [2019-10-01 17:29:04,279] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2019-10-01 17:29:04,280] - TelnetServer server is running on port 31000
  INFO root [2019-10-01 17:29:04,717] - ---- loginapp is running ----
 DEBUG root [2019-10-01 17:29:04,717] - Components::process(): Request for the process of identity...
  WARN root [2019-10-01 17:29:10,863] - Forwarding logs to logger[10.12.231.110:54713/0/0/0]...
 ERROR root [2019-10-01 17:30:08,433] - Components::removeComponentByChannel: logger : 2000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=118006116893, lastReceivedTime=117895926496, inactivityExceptionPeriod=599499425)
  INFO root [2019-10-01 17:30:08,436] - The following logs sent to logger failed:
  WARN root [2019-10-01 17:30:08,436] - ==> [2019-10-01 17:30:08 428] TCPPacketReceiver::processPendingEvents(10.12.231.110:54713): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2019-10-01 17:30:08,437] - ==> [2019-10-01 17:30:08 434] Components::removeComponentByChannel: logger : 2000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=118006116893, lastReceivedTime=117895926496, inactivityExceptionPeriod=599499425)
  WARN root [2019-10-01 17:30:08,502] - TCPPacketReceiver::processPendingEvents(10.12.231.110:54714): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2019-10-01 17:30:08,503] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=118006815569, lastReceivedTime=117897213767, inactivityExceptionPeriod=599499425)
  INFO root [2019-10-01 17:30:08,512] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [2019-10-01 17:30:08,512] - onLoginAppShutDown()
  INFO root [2019-10-01 17:30:08,512] - Shutdowner::onShutdown: shutting down
  INFO root [2019-10-01 17:30:08,512] - Shutdowner::onShutdownEnd: shutting down
  INFO root [2019-10-01 17:30:08,521] - Script::uninstall(): is successfully!
 DEBUG root [2019-10-01 17:30:08,522] - ThreadPool::destroy(): starting size 2.
  WARN root [2019-10-01 17:30:08,823] - ThreadPool::destroy(): waiting for thread(2)[0x1469fd0,0x146a038,], try=1
  INFO root [2019-10-01 22:37:40,750] - 
  INFO root [2019-10-01 22:37:40,766] - -----------------------------------------------------------------------------------------


  INFO root [2019-10-01 22:37:40,781] - Resmgr::initialize: KBE_ROOT=D:/kbengine/
  INFO root [2019-10-01 22:37:40,781] - Resmgr::initialize: KBE_RES_PATH=D:/kbengine/kbe/res/;D:/kbengine/BattleOfBalls_assets/;D:/kbengine/BattleOfBalls_assets/scripts/;D:/kbengine/BattleOfBalls_assets/res/
  INFO root [2019-10-01 22:37:40,781] - Resmgr::initialize: KBE_BIN_PATH=D:/kbengine/kbe/bin/server/
  INFO root [2019-10-01 22:37:40,828] - NetworkInterface::initialize(EXTERNAL-TCP): bound to all interfaces with default route interface on 127.0.0.1 ( 127.0.0.1:20013 )
  INFO root [2019-10-01 22:37:40,828] - NetworkInterface::initialize(EXTERNAL-TCP): address 127.0.0.1:20013, SOMAXCONN=128.
  INFO root [2019-10-01 22:37:40,844] - NetworkInterface::initialize(INTERNAL-TCP): bound to all interfaces with default route interface on 127.0.0.1 ( 127.0.0.1:49720 )
  INFO root [2019-10-01 22:37:40,844] - NetworkInterface::initialize(INTERNAL-TCP): address 127.0.0.1:49720, SOMAXCONN=128.
  INFO root [2019-10-01 22:37:40,844] - server-configs:
  INFO root [2019-10-01 22:37:40,844] - 	internalTcpAddr : 127.0.0.1:49720
  INFO root [2019-10-01 22:37:40,844] - 	externalTcpAddr : 127.0.0.1:20013
  INFO root [2019-10-01 22:37:40,844] - 	componentID : 9000
  WARN root [2019-10-01 22:37:41,000] - invalid UID(0) <= 0, please check UID for environment! automatically set to 41181.
  INFO root [2019-10-01 22:37:42,547] - ---- loginapp Version: 2.4.5. ScriptVersion: 0.1.0. Pythoncore: 3.7.3. Protocol: CE9FF53F4E85387EE4455C7191269324. Config: Debug X86. Built: 09:58:16 May  8 2019. AppID: 9000. UID: 41181. PID: 8392 ----
  INFO root [2019-10-01 22:37:42,547] - Server error_name: Intel(R) Core(TM) i5-6300HQ CPU @ 2.30GHz with 2097151kB RAM
  INFO root [2019-10-01 22:37:42,578] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2019-10-01 22:37:42,578] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
  INFO root [2019-10-01 22:37:42,859] - Script::install(): is successfully, Python=(3.7.3 (default, May  8 2019, 09:53:38) [MSC v.1916 32 bit (Intel)])!
  INFO root [2019-10-01 22:37:42,859] - Script::install(): KBExtra is successfully!
S_INFO root [2019-10-01 22:37:42,906] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2019-10-01 22:37:42,906] - TelnetServer server is running on port 31000
  INFO root [2019-10-01 22:37:43,343] - ---- loginapp is running ----
 DEBUG root [2019-10-01 22:37:43,343] - Components::process(): Request for the process of identity...
  INFO root [2019-10-01 22:37:50,670] - Components::findComponents: find logger(1)...
 ERROR root [2019-10-01 22:37:52,185] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [2019-10-01 22:37:52,185] - Components::findComponents: receive error!
  WARN root [2019-10-01 22:37:52,200] - Components::findComponents: not found logger!
  INFO root [2019-10-01 22:37:53,231] - Components::findComponents: find dbmgr(1)...
 ERROR root [2019-10-01 22:37:54,747] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [2019-10-01 22:37:54,747] - Components::findComponents: receive error!
  INFO root [2019-10-01 22:37:55,762] - Components::findComponents: find dbmgr(2)...
 ERROR root [2019-10-01 22:37:57,277] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [2019-10-01 22:37:57,277] - Components::findComponents: receive error!
  INFO root [2019-10-01 22:37:58,293] - Components::findComponents: find dbmgr(3)...
 ERROR root [2019-10-01 22:37:59,808] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [2019-10-01 22:37:59,808] - Components::findComponents: receive error!
  INFO root [2019-10-01 22:38:00,823] - Components::findComponents: find dbmgr(4)...
 ERROR root [2019-10-01 22:38:02,339] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [2019-10-01 22:38:02,339] - Components::findComponents: receive error!
  INFO root [2019-10-01 22:38:03,370] - Components::findComponents: find dbmgr(5)...
 ERROR root [2019-10-01 22:38:04,885] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [2019-10-01 22:38:04,885] - Components::findComponents: receive error!
  INFO root [2019-10-01 22:38:05,900] - Components::findComponents: find dbmgr(6)...
 ERROR root [2019-10-01 22:38:07,416] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [2019-10-01 22:38:07,416] - Components::findComponents: receive error!
  INFO root [2019-10-01 22:38:08,431] - Components::findComponents: find dbmgr(7)...
 ERROR root [2019-10-01 22:38:09,946] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [2019-10-01 22:38:09,946] - Components::findComponents: receive error!
  INFO root [2019-10-01 22:38:10,962] - Components::findComponents: find dbmgr(8)...
 ERROR root [2019-10-01 22:38:12,477] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [2019-10-01 22:38:12,477] - Components::findComponents: receive error!
  INFO root [2019-10-01 22:38:13,492] - Components::findComponents: find dbmgr(9)...
 ERROR root [2019-10-01 22:38:15,008] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [2019-10-01 22:38:15,008] - Components::findComponents: receive error!
  INFO root [2019-10-01 22:38:16,023] - Components::findComponents: find dbmgr(10)...
 ERROR root [2019-10-01 22:38:17,538] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [2019-10-01 22:38:17,538] - Components::findComponents: receive error!
  INFO root [2019-10-01 22:38:18,554] - Components::findComponents: find dbmgr(11)...
 ERROR root [2019-10-01 22:38:20,069] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [2019-10-01 22:38:20,069] - Components::findComponents: receive error!
  INFO root [2019-10-01 22:38:21,084] - Components::findComponents: find dbmgr(12)...
 ERROR root [2019-10-01 22:38:22,600] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [2019-10-01 22:38:22,600] - Components::findComponents: receive error!
  INFO root [2019-10-01 22:38:23,631] - Components::findComponents: find dbmgr(13)...
 ERROR root [2019-10-01 22:38:25,146] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [2019-10-01 22:38:25,146] - Components::findComponents: receive error!
  INFO root [2019-10-01 22:38:26,161] - Components::findComponents: find dbmgr(14)...
 ERROR root [2019-10-01 22:38:27,677] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [2019-10-01 22:38:27,677] - Components::findComponents: receive error!
  INFO root [2019-10-01 22:38:28,692] - Components::findComponents: find dbmgr(15)...
 ERROR root [2019-10-01 22:38:30,207] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [2019-10-01 22:38:30,207] - Components::findComponents: receive error!
  INFO root [2019-10-01 22:38:31,223] - Components::findComponents: find dbmgr(16)...
 ERROR root [2019-10-01 22:38:32,738] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [2019-10-01 22:38:32,738] - Components::findComponents: receive error!
  WARN root [2019-10-01 22:38:33,753] - Components::findComponents: find dbmgr(17)...
delay time is too long, please check the dbmgr logs!
 ERROR root [2019-10-01 22:38:35,268] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [2019-10-01 22:38:35,300] - Components::findComponents: receive error!
  WARN root [2019-10-01 22:38:36,331] - Components::findComponents: find dbmgr(18)...
delay time is too long, please check the dbmgr logs!
 ERROR root [2019-10-01 22:38:37,846] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [2019-10-01 22:38:37,846] - Components::findComponents: receive error!
  WARN root [2019-10-01 22:38:38,861] - Components::findComponents: find dbmgr(19)...
delay time is too long, please check the dbmgr logs!
 ERROR root [2019-10-01 22:38:40,377] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [2019-10-01 22:38:40,377] - Components::findComponents: receive error!
  WARN root [2019-10-01 22:38:41,392] - Components::findComponents: find dbmgr(20)...
delay time is too long, please check the dbmgr logs!
 ERROR root [2019-10-01 22:38:42,907] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [2019-10-01 22:38:42,907] - Components::findComponents: receive error!
  WARN root [2019-10-01 22:38:43,923] - Components::findComponents: find dbmgr(21)...
delay time is too long, please check the dbmgr logs!
 ERROR root [2019-10-01 22:38:45,438] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [2019-10-01 22:38:45,438] - Components::findComponents: receive error!
  WARN root [2019-10-01 22:38:46,453] - Components::findComponents: find dbmgr(22)...
delay time is too long, please check the dbmgr logs!
 ERROR root [2019-10-01 22:38:47,969] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [2019-10-01 22:38:47,969] - Components::findComponents: receive error!
  WARN root [2019-10-01 22:38:48,984] - Components::findComponents: find dbmgr(23)...
delay time is too long, please check the dbmgr logs!
 ERROR root [2019-10-01 22:38:50,499] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [2019-10-01 22:38:50,499] - Components::findComponents: receive error!
  WARN root [2019-10-01 22:38:51,530] - Components::findComponents: find dbmgr(24)...
delay time is too long, please check the dbmgr logs!
 ERROR root [2019-10-01 22:38:53,046] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [2019-10-01 22:38:53,046] - Components::findComponents: receive error!
  WARN root [2019-10-01 22:38:54,061] - Components::findComponents: find dbmgr(25)...
delay time is too long, please check the dbmgr logs!
 ERROR root [2019-10-01 22:38:55,576] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [2019-10-01 22:38:55,576] - Components::findComponents: receive error!
  WARN root [2019-10-01 22:38:56,592] - Components::findComponents: find dbmgr(26)...
delay time is too long, please check the dbmgr logs!
 ERROR root [2019-10-01 22:38:58,107] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [2019-10-01 22:38:58,107] - Components::findComponents: receive error!
  WARN root [2019-10-01 22:38:59,122] - Components::findComponents: find dbmgr(27)...
delay time is too long, please check the dbmgr logs!
 ERROR root [2019-10-01 22:39:00,638] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [2019-10-01 22:39:00,638] - Components::findComponents: receive error!
  WARN root [2019-10-01 22:39:01,653] - Components::findComponents: find dbmgr(28)...
delay time is too long, please check the dbmgr logs!
 ERROR root [2019-10-01 22:39:03,168] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [2019-10-01 22:39:03,168] - Components::findComponents: receive error!
  WARN root [2019-10-01 22:39:04,184] - Components::findComponents: find dbmgr(29)...
delay time is too long, please check the dbmgr logs!
 ERROR root [2019-10-01 22:39:05,699] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [2019-10-01 22:39:05,699] - Components::findComponents: receive error!
  WARN root [2019-10-01 22:39:06,730] - Components::findComponents: find dbmgr(30)...
delay time is too long, please check the dbmgr logs!
 ERROR root [2019-10-01 22:39:08,245] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [2019-10-01 22:39:08,245] - Components::findComponents: receive error!
  WARN root [2019-10-01 22:39:09,261] - Components::findComponents: find dbmgr(31)...
delay time is too long, please check the dbmgr logs!
 ERROR root [2019-10-01 22:39:10,776] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [2019-10-01 22:39:10,776] - Components::findComponents: receive error!
  WARN root [2019-10-01 22:39:11,791] - Components::findComponents: find dbmgr(32)...
delay time is too long, please check the dbmgr logs!
 ERROR root [2019-10-01 22:39:13,306] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [2019-10-01 22:39:13,306] - Components::findComponents: receive error!
  WARN root [2019-10-01 22:39:14,322] - Components::findComponents: find dbmgr(33)...
delay time is too long, please check the dbmgr logs!
 ERROR root [2019-10-01 22:39:15,837] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [2019-10-01 22:39:15,837] - Components::findComponents: receive error!
  WARN root [2019-10-01 22:39:16,852] - Components::findComponents: find dbmgr(34)...
delay time is too long, please check the dbmgr logs!
 ERROR root [2019-10-01 22:39:18,368] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [2019-10-01 22:39:18,368] - Components::findComponents: receive error!
  WARN root [2019-10-01 22:39:19,383] - Components::findComponents: find dbmgr(35)...
delay time is too long, please check the dbmgr logs!
 ERROR root [2019-10-01 22:39:20,898] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [2019-10-01 22:39:20,898] - Components::findComponents: receive error!
  WARN root [2019-10-01 22:39:21,914] - Components::findComponents: find dbmgr(36)...
delay time is too long, please check the dbmgr logs!
 ERROR root [2019-10-01 22:39:23,429] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [2019-10-01 22:39:23,429] - Components::findComponents: receive error!
  WARN root [2019-10-01 22:39:24,444] - Components::findComponents: find dbmgr(37)...
delay time is too long, please check the dbmgr logs!
 ERROR root [2019-10-01 22:39:25,960] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [2019-10-01 22:39:25,960] - Components::findComponents: receive error!
  WARN root [2019-10-01 22:39:26,991] - Components::findComponents: find dbmgr(38)...
delay time is too long, please check the dbmgr logs!
 ERROR root [2019-10-01 22:39:28,506] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [2019-10-01 22:39:28,506] - Components::findComponents: receive error!
  WARN root [2019-10-01 22:39:29,521] - Components::findComponents: find dbmgr(39)...
delay time is too long, please check the dbmgr logs!
 ERROR root [2019-10-01 22:39:31,037] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [2019-10-01 22:39:31,037] - Components::findComponents: receive error!
  WARN root [2019-10-01 22:39:32,052] - Components::findComponents: find dbmgr(40)...
delay time is too long, please check the dbmgr logs!
 ERROR root [2019-10-01 22:39:33,567] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [2019-10-01 22:39:33,567] - Components::findComponents: receive error!
  WARN root [2019-10-01 22:39:34,583] - Components::findComponents: find dbmgr(41)...
delay time is too long, please check the dbmgr logs!
 ERROR root [2019-10-01 22:39:36,098] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [2019-10-01 22:39:36,098] - Components::findComponents: receive error!
  WARN root [2019-10-01 22:39:37,113] - Components::findComponents: find dbmgr(42)...
delay time is too long, please check the dbmgr logs!
 ERROR root [2019-10-01 22:39:38,629] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [2019-10-01 22:39:38,629] - Components::findComponents: receive error!
  WARN root [2019-10-01 22:39:39,644] - Components::findComponents: find dbmgr(43)...
delay time is too long, please check the dbmgr logs!
 ERROR root [2019-10-01 22:39:41,159] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [2019-10-01 22:39:41,159] - Components::findComponents: receive error!
  WARN root [2019-10-01 22:39:42,190] - Components::findComponents: find dbmgr(44)...
delay time is too long, please check the dbmgr logs!
 ERROR root [2019-10-01 22:39:43,706] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [2019-10-01 22:39:43,706] - Components::findComponents: receive error!
  WARN root [2019-10-01 22:39:44,721] - Components::findComponents: find dbmgr(45)...
delay time is too long, please check the dbmgr logs!
 ERROR root [2019-10-01 22:39:46,236] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [2019-10-01 22:39:46,236] - Components::findComponents: receive error!
  WARN root [2019-10-01 22:39:47,252] - Components::findComponents: find dbmgr(46)...
delay time is too long, please check the dbmgr logs!
 ERROR root [2019-10-01 22:39:48,767] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [2019-10-01 22:39:48,767] - Components::findComponents: receive error!
  WARN root [2019-10-01 22:39:49,782] - Components::findComponents: find dbmgr(47)...
delay time is too long, please check the dbmgr logs!
 ERROR root [2019-10-01 22:39:51,298] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [2019-10-01 22:39:51,298] - Components::findComponents: receive error!
  WARN root [2019-10-01 22:39:52,313] - Components::findComponents: find dbmgr(48)...
delay time is too long, please check the dbmgr logs!
 ERROR root [2019-10-01 22:39:53,815] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [2019-10-01 22:39:53,815] - Components::findComponents: receive error!
  WARN root [2019-10-01 22:39:54,830] - Components::findComponents: find dbmgr(49)...
delay time is too long, please check the dbmgr logs!
 ERROR root [2019-10-01 22:39:56,346] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [2019-10-01 22:39:56,346] - Components::findComponents: receive error!
  WARN root [2019-10-01 22:39:57,361] - Components::findComponents: find dbmgr(50)...
delay time is too long, please check the dbmgr logs!
 ERROR root [2019-10-01 22:39:58,876] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [2019-10-01 22:39:58,876] - Components::findComponents: receive error!
  WARN root [2019-10-01 22:39:59,892] - Components::findComponents: find dbmgr(51)...
delay time is too long, please check the dbmgr logs!
 ERROR root [2019-10-01 22:40:01,407] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [2019-10-01 22:40:01,407] - Components::findComponents: receive error!
  WARN root [2019-10-01 22:40:02,422] - Components::findComponents: find dbmgr(52)...
delay time is too long, please check the dbmgr logs!
 ERROR root [2019-10-01 22:40:03,938] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [2019-10-01 22:40:03,938] - Components::findComponents: receive error!
  WARN root [2019-10-01 22:40:04,953] - Components::findComponents: find dbmgr(53)...
delay time is too long, please check the dbmgr logs!
 ERROR root [2019-10-01 22:40:06,468] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [2019-10-01 22:40:06,468] - Components::findComponents: receive error!
  WARN root [2019-10-01 22:40:07,484] - Components::findComponents: find dbmgr(54)...
delay time is too long, please check the dbmgr logs!
 ERROR root [2019-10-01 22:40:08,999] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [2019-10-01 22:40:08,999] - Components::findComponents: receive error!
  WARN root [2019-10-01 22:40:10,030] - Components::findComponents: find dbmgr(55)...
delay time is too long, please check the dbmgr logs!
 ERROR root [2019-10-01 22:40:11,545] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [2019-10-01 22:40:11,545] - Components::findComponents: receive error!
  WARN root [2019-10-01 22:40:12,561] - Components::findComponents: find dbmgr(56)...
delay time is too long, please check the dbmgr logs!
 ERROR root [2019-10-01 22:40:14,076] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [2019-10-01 22:40:14,076] - Components::findComponents: receive error!
  WARN root [2019-10-01 22:40:15,091] - Components::findComponents: find dbmgr(57)...
delay time is too long, please check the dbmgr logs!
 ERROR root [2019-10-01 22:40:16,607] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [2019-10-01 22:40:16,607] - Components::findComponents: receive error!
  WARN root [2019-10-01 22:40:17,622] - Components::findComponents: find dbmgr(58)...
delay time is too long, please check the dbmgr logs!
 ERROR root [2019-10-01 22:40:19,137] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [2019-10-01 22:40:19,137] - Components::findComponents: receive error!
  WARN root [2019-10-01 22:40:20,152] - Components::findComponents: find dbmgr(59)...
delay time is too long, please check the dbmgr logs!
 ERROR root [2019-10-01 22:40:21,668] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [2019-10-01 22:40:21,668] - Components::findComponents: receive error!
  WARN root [2019-10-01 22:40:22,683] - Components::findComponents: find dbmgr(60)...
delay time is too long, please check the dbmgr logs!
 ERROR root [2019-10-01 22:40:24,198] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [2019-10-01 22:40:24,198] - Components::findComponents: receive error!
  WARN root [2019-10-01 22:40:25,214] - Components::findComponents: find dbmgr(61)...
delay time is too long, please check the dbmgr logs!
 ERROR root [2019-10-01 22:40:26,729] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [2019-10-01 22:40:26,729] - Components::findComponents: receive error!
  WARN root [2019-10-01 22:40:27,744] - Components::findComponents: find dbmgr(62)...
delay time is too long, please check the dbmgr logs!
 ERROR root [2019-10-01 22:40:29,260] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [2019-10-01 22:40:29,260] - Components::findComponents: receive error!
  WARN root [2019-10-01 22:40:30,291] - Components::findComponents: find dbmgr(63)...
delay time is too long, please check the dbmgr logs!
 ERROR root [2019-10-01 22:40:31,806] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [2019-10-01 22:40:31,806] - Components::findComponents: receive error!
  WARN root [2019-10-01 22:40:32,821] - Components::findComponents: find dbmgr(64)...
delay time is too long, please check the dbmgr logs!
 ERROR root [2019-10-01 22:40:34,337] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [2019-10-01 22:40:34,337] - Components::findComponents: receive error!
  WARN root [2019-10-01 22:40:35,352] - Components::findComponents: find dbmgr(65)...
delay time is too long, please check the dbmgr logs!
 ERROR root [2019-10-01 22:40:36,867] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [2019-10-01 22:40:36,867] - Components::findComponents: receive error!
  WARN root [2019-10-01 22:40:37,883] - Components::findComponents: find dbmgr(66)...
delay time is too long, please check the dbmgr logs!
 ERROR root [2019-10-01 22:40:39,398] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [2019-10-01 22:40:39,398] - Components::findComponents: receive error!
  WARN root [2019-10-01 22:40:40,413] - Components::findComponents: find dbmgr(67)...
delay time is too long, please check the dbmgr logs!
 ERROR root [2019-10-01 22:40:41,929] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [2019-10-01 22:40:41,929] - Components::findComponents: receive error!
  WARN root [2019-10-01 22:40:42,944] - Components::findComponents: find dbmgr(68)...
delay time is too long, please check the dbmgr logs!
 ERROR root [2019-10-01 22:40:44,459] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [2019-10-01 22:40:44,459] - Components::findComponents: receive error!
  WARN root [2019-10-01 22:40:45,490] - Components::findComponents: find dbmgr(69)...
delay time is too long, please check the dbmgr logs!
 ERROR root [2019-10-01 22:40:47,006] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [2019-10-01 22:40:47,006] - Components::findComponents: receive error!
  WARN root [2019-10-01 22:40:48,021] - Components::findComponents: find dbmgr(70)...
delay time is too long, please check the dbmgr logs!
 ERROR root [2019-10-01 22:40:49,536] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [2019-10-01 22:40:49,536] - Components::findComponents: receive error!
  WARN root [2019-10-01 22:40:50,552] - Components::findComponents: find dbmgr(71)...
delay time is too long, please check the dbmgr logs!
 ERROR root [2019-10-01 22:40:52,067] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [2019-10-01 22:40:52,067] - Components::findComponents: receive error!
  WARN root [2019-10-01 22:40:53,082] - Components::findComponents: find dbmgr(72)...
delay time is too long, please check the dbmgr logs!
 ERROR root [2019-10-01 22:40:54,597] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [2019-10-01 22:40:54,597] - Components::findComponents: receive error!
  WARN root [2019-10-01 22:40:55,613] - Components::findComponents: find dbmgr(73)...
delay time is too long, please check the dbmgr logs!
 ERROR root [2019-10-01 22:40:57,128] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [2019-10-01 22:40:57,128] - Components::findComponents: receive error!
  WARN root [2019-10-01 22:40:58,144] - Components::findComponents: find dbmgr(74)...
delay time is too long, please check the dbmgr logs!
 ERROR root [2019-10-01 22:40:59,659] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [2019-10-01 22:40:59,659] - Components::findComponents: receive error!
  WARN root [2019-10-01 22:41:00,690] - Components::findComponents: find dbmgr(75)...
delay time is too long, please check the dbmgr logs!
 ERROR root [2019-10-01 22:41:02,205] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [2019-10-01 22:41:02,205] - Components::findComponents: receive error!
  WARN root [2019-10-01 22:41:03,220] - Components::findComponents: find dbmgr(76)...
delay time is too long, please check the dbmgr logs!
 ERROR root [2019-10-01 22:41:04,736] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [2019-10-01 22:41:04,736] - Components::findComponents: receive error!
  WARN root [2019-10-01 22:41:05,751] - Components::findComponents: find dbmgr(77)...
delay time is too long, please check the dbmgr logs!
 ERROR root [2019-10-01 22:41:07,266] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [2019-10-01 22:41:07,266] - Components::findComponents: receive error!
  WARN root [2019-10-01 22:41:08,282] - Components::findComponents: find dbmgr(78)...
delay time is too long, please check the dbmgr logs!
 ERROR root [2019-10-01 22:41:09,797] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [2019-10-01 22:41:09,797] - Components::findComponents: receive error!
  WARN root [2019-10-01 22:41:10,813] - Components::findComponents: find dbmgr(79)...
delay time is too long, please check the dbmgr logs!
 ERROR root [2019-10-01 22:41:12,328] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [2019-10-01 22:41:12,328] - Components::findComponents: receive error!
  WARN root [2019-10-01 22:41:13,343] - Components::findComponents: find dbmgr(80)...
delay time is too long, please check the dbmgr logs!
 ERROR root [2019-10-01 22:41:14,858] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [2019-10-01 22:41:14,858] - Components::findComponents: receive error!
  WARN root [2019-10-01 22:41:15,874] - Components::findComponents: find dbmgr(81)...
delay time is too long, please check the dbmgr logs!
 ERROR root [2019-10-01 22:41:17,389] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [2019-10-01 22:41:17,389] - Components::findComponents: receive error!
  WARN root [2019-10-01 22:41:18,404] - Components::findComponents: find dbmgr(82)...
delay time is too long, please check the dbmgr logs!
 ERROR root [2019-10-01 22:41:19,920] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [2019-10-01 22:41:19,920] - Components::findComponents: receive error!
  WARN root [2019-10-01 22:41:20,935] - Components::findComponents: find dbmgr(83)...
delay time is too long, please check the dbmgr logs!
 ERROR root [2019-10-01 22:41:22,450] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [2019-10-01 22:41:22,450] - Components::findComponents: receive error!
  WARN root [2019-10-01 22:41:23,466] - Components::findComponents: find dbmgr(84)...
delay time is too long, please check the dbmgr logs!
 ERROR root [2019-10-01 22:41:24,981] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [2019-10-01 22:41:24,981] - Components::findComponents: receive error!
  WARN root [2019-10-01 22:41:26,012] - Components::findComponents: find dbmgr(85)...
delay time is too long, please check the dbmgr logs!
 ERROR root [2019-10-01 22:41:27,527] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [2019-10-01 22:41:27,527] - Components::findComponents: receive error!
  WARN root [2019-10-01 22:41:28,543] - Components::findComponents: find dbmgr(86)...
delay time is too long, please check the dbmgr logs!
 ERROR root [2019-10-01 22:41:30,058] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [2019-10-01 22:41:30,058] - Components::findComponents: receive error!
  WARN root [2019-10-01 22:41:31,073] - Components::findComponents: find dbmgr(87)...
delay time is too long, please check the dbmgr logs!
 ERROR root [2019-10-01 22:41:32,589] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [2019-10-01 22:41:32,589] - Components::findComponents: receive error!
  WARN root [2019-10-01 22:41:33,604] - Components::findComponents: find dbmgr(88)...
delay time is too long, please check the dbmgr logs!
 ERROR root [2019-10-01 22:41:35,119] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [2019-10-01 22:41:35,119] - Components::findComponents: receive error!
  WARN root [2019-10-01 22:41:36,135] - Components::findComponents: find dbmgr(89)...
delay time is too long, please check the dbmgr logs!
 ERROR root [2019-10-01 22:41:37,650] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [2019-10-01 22:41:37,650] - Components::findComponents: receive error!
  WARN root [2019-10-01 22:41:38,665] - Components::findComponents: find dbmgr(90)...
delay time is too long, please check the dbmgr logs!
 ERROR root [2019-10-01 22:41:40,181] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [2019-10-01 22:41:40,181] - Components::findComponents: receive error!
  WARN root [2019-10-01 22:41:41,212] - Components::findComponents: find dbmgr(91)...
delay time is too long, please check the dbmgr logs!
 ERROR root [2019-10-01 22:41:42,727] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [2019-10-01 22:41:42,727] - Components::findComponents: receive error!
  WARN root [2019-10-01 22:41:43,742] - Components::findComponents: find dbmgr(92)...
delay time is too long, please check the dbmgr logs!
 ERROR root [2019-10-01 22:41:45,258] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [2019-10-01 22:41:45,258] - Components::findComponents: receive error!
  WARN root [2019-10-01 22:41:46,273] - Components::findComponents: find dbmgr(93)...
delay time is too long, please check the dbmgr logs!
 ERROR root [2019-10-01 22:41:47,788] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [2019-10-01 22:41:47,788] - Components::findComponents: receive error!
  WARN root [2019-10-01 22:41:48,804] - Components::findComponents: find dbmgr(94)...
delay time is too long, please check the dbmgr logs!
 ERROR root [2019-10-01 22:41:50,319] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [2019-10-01 22:41:50,319] - Components::findComponents: receive error!
  WARN root [2019-10-01 22:41:51,334] - Components::findComponents: find dbmgr(95)...
delay time is too long, please check the dbmgr logs!
 ERROR root [2019-10-01 22:41:52,850] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [2019-10-01 22:41:52,850] - Components::findComponents: receive error!
  WARN root [2019-10-01 22:41:53,865] - Components::findComponents: find dbmgr(96)...
delay time is too long, please check the dbmgr logs!
 ERROR root [2019-10-01 22:41:55,380] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [2019-10-01 22:41:55,380] - Components::findComponents: receive error!
  WARN root [2019-10-01 22:41:56,411] - Components::findComponents: find dbmgr(97)...
delay time is too long, please check the dbmgr logs!
 ERROR root [2019-10-01 22:41:57,926] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [2019-10-01 22:41:57,926] - Components::findComponents: receive error!
